######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 16:13:18
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '10.0', '10.0', '10.0')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('253', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Mesh__Structure__Delete_Selection()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '0.5', '0.5', '0.5')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('3', '0')
Process.Stack__Segmentation__Fill_Label('88', '0')
Process.Stack__Segmentation__Fill_Label('80', '0')
Process.Stack__Segmentation__Fill_Label('103', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('93', '0')
Process.Stack__Segmentation__Fill_Label('35', '0')
Process.Stack__Segmentation__Fill_Label('19', '0')
Process.Stack__Segmentation__Fill_Label('100', '0')
Process.Stack__Segmentation__Fill_Label('8', '0')
Process.Stack__Segmentation__Fill_Label('138', '0')
Process.Stack__Segmentation__Fill_Label('69', '0')
Process.Stack__Segmentation__Fill_Label('68', '0')
Process.Stack__Segmentation__Fill_Label('111', '0')
Process.Stack__Segmentation__Fill_Label('87', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('109', '0')
Process.Stack__Segmentation__Fill_Label('97', '0')
Process.Stack__Segmentation__Fill_Label('112', '0')
Process.Stack__Segmentation__Fill_Label('53', '0')
Process.Stack__Segmentation__Fill_Label('135', '0')
Process.Stack__Segmentation__Fill_Label('129', '0')
Process.Stack__Segmentation__Fill_Label('28', '0')
Process.Stack__Segmentation__Fill_Label('98', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.5 1.5 1.5', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '800')
Process.Stack__Segmentation__Fill_Label('109', '0')
Process.Stack__Segmentation__Fill_Label('231', '0')
Process.Stack__Segmentation__Fill_Label('20', '0')
Process.Stack__Segmentation__Fill_Label('203', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('1', '0')
Process.Stack__Segmentation__Fill_Label('262', '0')
Process.Stack__Segmentation__Fill_Label('227', '0')
Process.Stack__Segmentation__Fill_Label('283', '0')
Process.Stack__Segmentation__Fill_Label('228', '0')
Process.Stack__Segmentation__Fill_Label('153', '0')
Process.Stack__Segmentation__Fill_Label('303', '0')
Process.Stack__Segmentation__Fill_Label('158', '0')
Process.Stack__Segmentation__Fill_Label('218', '0')
Process.Stack__Segmentation__Fill_Label('222', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('302', '0')
Process.Stack__Segmentation__Fill_Label('111', '0')
Process.Stack__Segmentation__Fill_Label('24', '0')
Process.Stack__Segmentation__Fill_Label('51', '0')
Process.Stack__Segmentation__Fill_Label('68', '0')
Process.Stack__Segmentation__Fill_Label('85', '0')
Process.Stack__Segmentation__Fill_Label('288', '0')
Process.Stack__Segmentation__Fill_Label('82', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_5/Ac_DA_2_5_2023_09_11__13_58_58_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 14:36:59

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Main', '0', '')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__Segmentation__Fill_Label('202', '256')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Work', '0', '')
Process.Stack__Segmentation__Fill_Label('202', '256')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Work', '0', '')
Process.Stack__Segmentation__Fill_Label('202', '250')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 14:40:45
Process.Misc__System__Save_View('')
Process.Stack__Canvas__Change_Voxel_Size('1.0', '1.0', '1.0')
Process.Stack__Canvas__Change_Voxel_Size('1', '1', '2')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Work', '0', '')
Process.Stack__Canvas__Change_Voxel_Size('1', '1', '2')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 11:41:49
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out_CNN.tif', 'Main', '0', '')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_mesh.mgxm', 'no', 'no', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_5/Ac_DA_2_5_2023_09_11__13_58_58_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:11:23
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_mesh.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:11:32

Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_5/Ac_DA_2_5_mesh.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:16:40
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_5/Ac_DA_2_5_mesh.mgxm', 'no', 'no', '0')
