######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 16:03:30
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_2023_09_11__13_53_21_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('345', '0')
Process.Stack__Segmentation__Fill_Label('223', '0')
Process.Stack__Segmentation__Fill_Label('309', '0')
Process.Stack__Segmentation__Fill_Label('164', '0')
Process.Stack__Segmentation__Fill_Label('271', '0')
Process.Stack__Segmentation__Fill_Label('118', '0')
Process.Stack__Segmentation__Fill_Label('141', '0')
Process.Stack__Segmentation__Fill_Label('272', '0')
Process.Stack__Segmentation__Fill_Label('267', '0')
Process.Stack__Segmentation__Fill_Label('80', '0')
Process.Stack__Segmentation__Fill_Label('23', '0')
Process.Stack__Segmentation__Fill_Label('9', '0')
Process.Stack__Segmentation__Fill_Label('186', '0')
Process.Stack__Segmentation__Fill_Label('167', '0')
Process.Stack__Segmentation__Fill_Label('200', '0')
Process.Stack__Segmentation__Fill_Label('256', '0')
Process.Stack__Segmentation__Fill_Label('338', '0')
Process.Stack__Segmentation__Fill_Label('44', '0')
Process.Stack__Segmentation__Fill_Label('127', '0')
Process.Stack__Segmentation__Fill_Label('1', '0')
Process.Stack__Segmentation__Fill_Label('153', '0')
Process.Stack__Segmentation__Fill_Label('211', '0')
Process.Stack__Segmentation__Fill_Label('319', '0')
Process.Stack__Segmentation__Fill_Label('182', '0')
Process.Stack__Segmentation__Fill_Label('8', '0')
Process.Stack__Segmentation__Fill_Label('373', '0')
Process.Stack__Segmentation__Fill_Label('275', '0')
Process.Stack__Segmentation__Fill_Label('71', '0')
Process.Stack__Segmentation__Fill_Label('348', '0')
Process.Stack__Segmentation__Fill_Label('83', '0')
Process.Stack__Segmentation__Fill_Label('36', '0')
Process.Stack__Segmentation__Fill_Label('369', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('352', '0')
Process.Stack__Segmentation__Fill_Label('320', '0')
Process.Stack__Segmentation__Fill_Label('363', '0')
Process.Stack__Segmentation__Fill_Label('60', '0')
Process.Stack__Segmentation__Fill_Label('354', '0')
Process.Stack__Segmentation__Fill_Label('277', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 15:27:52

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('175', '0')
Process.Stack__Segmentation__Fill_Label('87', '0')
Process.Stack__Segmentation__Fill_Label('278', '0')
Process.Stack__Segmentation__Fill_Label('152', '0')
Process.Stack__Segmentation__Fill_Label('125', '0')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '0.5', '0.5', '0.5')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('493', '0')
Process.Stack__Segmentation__Fill_Label('74', '0')
Process.Stack__Segmentation__Fill_Label('424', '0')
Process.Stack__Segmentation__Fill_Label('350', '0')
Process.Stack__Segmentation__Fill_Label('309', '0')
Process.Stack__Segmentation__Fill_Label('178', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '0.5', '0.5', '0.5')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '800')
Process.Stack__Segmentation__Fill_Label('26', '0')
Process.Stack__Segmentation__Fill_Label('46', '0')
Process.Stack__Segmentation__Fill_Label('104', '0')
Process.Stack__Segmentation__Fill_Label('74', '0')
Process.Stack__Segmentation__Fill_Label('454', '0')
Process.Stack__Segmentation__Fill_Label('263', '0')
Process.Stack__Segmentation__Fill_Label('334', '0')
Process.Stack__Segmentation__Fill_Label('138', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('462', '0')
Process.Stack__Segmentation__Fill_Label('144', '0')
Process.Stack__Segmentation__Fill_Label('227', '0')
Process.Stack__Segmentation__Fill_Label('6', '0')
Process.Stack__Segmentation__Fill_Label('111', '0')
Process.Stack__Segmentation__Fill_Label('459', '0')
Process.Stack__Segmentation__Fill_Label('295', '0')
Process.Stack__Segmentation__Fill_Label('112', '0')
Process.Stack__Segmentation__Fill_Label('45', '0')
Process.Stack__Segmentation__Fill_Label('396', '0')
Process.Stack__Segmentation__Fill_Label('109', '0')
Process.Stack__Segmentation__Fill_Label('417', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.2 1.2 1.2', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('378', '0')
Process.Stack__Segmentation__Fill_Label('157', '0')
Process.Stack__Segmentation__Fill_Label('330', '0')
Process.Stack__Segmentation__Fill_Label('285', '0')
Process.Stack__Segmentation__Fill_Label('31', '0')
Process.Stack__Segmentation__Fill_Label('351', '0')
Process.Stack__Segmentation__Fill_Label('226', '0')
Process.Stack__Segmentation__Fill_Label('150', '0')
Process.Stack__Segmentation__Fill_Label('182', '0')
Process.Stack__Segmentation__Fill_Label('162', '0')
Process.Stack__Segmentation__Fill_Label('4', '0')
Process.Stack__Segmentation__Fill_Label('188', '0')
Process.Stack__Segmentation__Fill_Label('431', '0')
Process.Stack__Segmentation__Fill_Label('412', '0')
Process.Stack__Segmentation__Fill_Label('160', '0')
Process.Stack__Segmentation__Fill_Label('443', '0')
Process.Stack__Segmentation__Fill_Label('22', '0')
Process.Stack__Segmentation__Fill_Label('168', '0')
Process.Stack__Segmentation__Fill_Label('35', '0')
Process.Stack__Segmentation__Fill_Label('209', '0')
Process.Stack__Segmentation__Fill_Label('88', '0')
Process.Stack__Segmentation__Fill_Label('47', '0')
Process.Stack__Segmentation__Fill_Label('469', '0')
Process.Stack__Segmentation__Fill_Label('6', '0')
Process.Stack__Segmentation__Fill_Label('241', '0')
Process.Stack__Segmentation__Fill_Label('196', '0')
Process.Stack__Segmentation__Fill_Label('463', '0')
Process.Stack__Segmentation__Fill_Label('132', '0')
Process.Stack__Segmentation__Fill_Label('347', '0')
Process.Stack__Segmentation__Fill_Label('91', '0')
Process.Stack__Segmentation__Fill_Label('333', '0')
Process.Stack__Segmentation__Fill_Label('202', '0')
Process.Stack__Segmentation__Fill_Label('440', '0')
Process.Stack__Segmentation__Fill_Label('317', '0')
Process.Stack__Segmentation__Fill_Label('101', '0')
Process.Stack__Segmentation__Fill_Label('401', '0')
Process.Stack__Segmentation__Fill_Label('147', '0')
Process.Stack__Segmentation__Fill_Label('374', '0')
Process.Stack__Segmentation__Fill_Label('1', '0')
Process.Stack__Segmentation__Fill_Label('108', '0')
Process.Stack__Segmentation__Fill_Label('346', '0')
Process.Stack__Segmentation__Fill_Label('450', '0')
Process.Stack__Segmentation__Fill_Label('98', '0')
Process.Stack__Segmentation__Fill_Label('279', '0')
Process.Stack__Segmentation__Fill_Label('193', '0')
Process.Stack__Segmentation__Fill_Label('365', '0')
Process.Stack__Segmentation__Fill_Label('177', '0')
Process.Stack__Segmentation__Fill_Label('385', '0')
Process.Stack__Segmentation__Fill_Label('65', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('305', '0')
Process.Stack__Segmentation__Fill_Label('274', '0')
Process.Stack__Segmentation__Fill_Label('145', '0')
Process.Stack__Segmentation__Fill_Label('404', '0')
Process.Stack__Segmentation__Fill_Label('130', '0')
Process.Stack__Segmentation__Fill_Label('120', '0')
Process.Stack__Segmentation__Fill_Label('222', '0')
Process.Stack__Segmentation__Fill_Label('74', '0')
Process.Stack__Segmentation__Fill_Label('455', '0')
Process.Stack__Segmentation__Fill_Label('213', '0')
Process.Stack__Segmentation__Fill_Label('362', '0')
Process.Stack__Segmentation__Fill_Label('363', '0')
Process.Stack__Segmentation__Fill_Label('275', '0')
Process.Stack__Segmentation__Fill_Label('435', '0')
Process.Stack__Segmentation__Fill_Label('125', '0')
Process.Stack__Segmentation__Fill_Label('115', '0')
Process.Stack__Segmentation__Fill_Label('17', '0')
Process.Stack__Segmentation__Fill_Label('131', '0')
Process.Stack__Segmentation__Fill_Label('58', '0')
Process.Stack__Segmentation__Fill_Label('206', '0')
Process.Stack__Segmentation__Fill_Label('56', '0')
Process.Stack__Segmentation__Fill_Label('143', '0')
Process.Stack__Segmentation__Fill_Label('357', '0')
Process.Stack__Segmentation__Fill_Label('230', '0')
Process.Stack__Segmentation__Fill_Label('253', '0')
Process.Stack__Segmentation__Fill_Label('10', '0')
Process.Stack__Segmentation__Fill_Label('49', '0')
Process.Stack__Segmentation__Fill_Label('243', '0')
Process.Stack__Segmentation__Fill_Label('438', '0')
Process.Stack__Segmentation__Fill_Label('359', '0')
Process.Stack__Segmentation__Fill_Label('159', '0')
Process.Stack__Segmentation__Fill_Label('180', '0')
Process.Stack__Segmentation__Fill_Label('411', '0')
Process.Stack__Segmentation__Fill_Label('34', '0')
Process.Stack__Segmentation__Fill_Label('328', '0')
Process.Stack__Segmentation__Fill_Label('45', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('341', '0')
Process.Stack__Segmentation__Fill_Label('393', '0')
Process.Stack__Segmentation__Fill_Label('186', '0')
Process.Stack__Segmentation__Fill_Label('137', '0')
Process.Stack__Segmentation__Fill_Label('33', '0')
Process.Stack__Segmentation__Fill_Label('251', '0')
Process.Stack__Segmentation__Fill_Label('228', '0')
Process.Stack__Segmentation__Fill_Label('415', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('102', '0')
Process.Stack__Segmentation__Fill_Label('451', '0')
Process.Stack__Segmentation__Fill_Label('421', '0')
Process.Stack__Segmentation__Fill_Label('75', '0')
Process.Stack__Segmentation__Fill_Label('367', '0')
Process.Stack__Segmentation__Fill_Label('381', '0')
Process.Stack__Segmentation__Fill_Label('185', '0')
Process.Stack__Segmentation__Fill_Label('407', '0')
Process.Stack__Segmentation__Fill_Label('116', '0')
Process.Stack__Segmentation__Fill_Label('300', '0')
Process.Stack__Segmentation__Fill_Label('259', '0')
Process.Stack__Segmentation__Fill_Label('394', '103')
Process.Stack__Segmentation__Fill_Label('390', '44')
Process.Stack__Segmentation__Fill_Label('178', '103')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__Segmentation__Fill_Label('103', '343')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 15:41:58
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 11:40:37
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_2023_09_11__13_53_21_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_2023_09_11__13_53_21_Out_CNN.tif', 'Main', '0', '')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('250', '0')
Process.Stack__Segmentation__Fill_Label('79', '0')
Process.Stack__Segmentation__Fill_Label('298', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('64', '0')
Process.Stack__Segmentation__Fill_Label('246', '0')
Process.Stack__Segmentation__Fill_Label('63', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_2023_09_11__13_56_03_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:08:13

Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_2023_09_11__13_53_21_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('16.0')
Process.Stack__Filters__Brighten_Darken('16.0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '3', '3', '3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '1.5', '1.5', '1.5')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_mesh.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:16:27
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_4/Ac_DA_2_4_mesh.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-06 16:18:55
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_final.mgxv')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh2.mgxm', 'no', 'no', '0')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
