######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 09:51:22

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1200')
Process.Stack__Segmentation__Fill_Label('202', '0')
Process.Stack__Segmentation__Fill_Label('86', '0')
Process.Stack__Segmentation__Fill_Label('11', '0')
Process.Stack__Segmentation__Fill_Label('211', '0')
Process.Stack__Segmentation__Fill_Label('165', '0')
Process.Stack__Segmentation__Fill_Label('96', '0')
Process.Stack__Segmentation__Fill_Label('7', '0')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__Segmentation__Fill_Label('84', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('42', '0')
Process.Stack__Segmentation__Fill_Label('170', '0')
Process.Stack__Segmentation__Fill_Label('108', '0')
Process.Stack__Segmentation__Fill_Label('5', '0')
Process.Stack__Segmentation__Fill_Label('147', '0')
Process.Stack__Segmentation__Fill_Label('210', '0')
Process.Stack__Segmentation__Fill_Label('216', '0')
Process.Stack__Segmentation__Fill_Label('155', '0')
Process.Stack__Segmentation__Fill_Label('203', '0')
Process.Stack__Segmentation__Fill_Label('198', '0')
Process.Stack__Segmentation__Fill_Label('158', '0')
Process.Stack__Segmentation__Fill_Label('172', '0')
Process.Stack__Segmentation__Fill_Label('127', '0')
Process.Stack__Segmentation__Fill_Label('124', '0')
Process.Stack__Segmentation__Fill_Label('82', '0')
Process.Stack__Segmentation__Fill_Label('121', '0')
Process.Stack__Segmentation__Fill_Label('212', '0')
Process.Stack__Segmentation__Fill_Label('204', '0')
Process.Stack__Segmentation__Fill_Label('213', '0')
Process.Stack__Segmentation__Fill_Label('24', '0')
Process.Stack__Segmentation__Fill_Label('72', '0')
Process.Stack__Segmentation__Fill_Label('157', '0')
Process.Stack__Segmentation__Fill_Label('195', '0')
Process.Stack__Segmentation__Fill_Label('75', '0')
Process.Stack__Segmentation__Fill_Label('133', '0')
Process.Stack__Segmentation__Fill_Label('141', '0')
Process.Stack__Segmentation__Fill_Label('83', '0')
Process.Stack__Segmentation__Fill_Label('97', '0')
Process.Stack__Segmentation__Fill_Label('106', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('73', '0')
Process.Stack__Segmentation__Fill_Label('68', '0')
Process.Stack__Segmentation__Fill_Label('91', '0')
Process.Stack__Segmentation__Fill_Label('16', '0')
Process.Stack__Segmentation__Fill_Label('78', '0')
Process.Stack__Segmentation__Fill_Label('196', '0')
Process.Stack__Segmentation__Fill_Label('151', '0')
Process.Stack__Segmentation__Fill_Label('95', '0')
Process.Stack__Segmentation__Fill_Label('104', '0')
Process.Stack__Segmentation__Fill_Label('92', '0')
Process.Stack__Segmentation__Fill_Label('194', '0')
Process.Stack__Segmentation__Fill_Label('143', '0')
Process.Stack__Segmentation__Fill_Label('60', '0')
Process.Stack__Segmentation__Fill_Label('132', '0')
Process.Stack__Segmentation__Fill_Label('125', '0')
Process.Stack__Segmentation__Fill_Label('53', '0')
Process.Stack__Segmentation__Fill_Label('179', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('58', '0')
Process.Stack__Segmentation__Fill_Label('100', '0')
Process.Stack__Segmentation__Fill_Label('134', '0')
Process.Stack__Segmentation__Fill_Label('130', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('65', '15')
Process.Stack__Segmentation__Fill_Label('182', '15')
Process.Stack__Segmentation__Fill_Label('46', '15')
Process.Stack__Segmentation__Fill_Label('207', '15')
Process.Stack__Segmentation__Fill_Label('191', '112')
Process.Stack__Segmentation__Fill_Label('112', '112')
Process.Stack__Segmentation__Fill_Label('175', '112')
Process.Stack__Segmentation__Fill_Label('154', '112')
Process.Stack__Segmentation__Fill_Label('135', '112')
Process.Stack__Segmentation__Fill_Label('167', '112')
Process.Stack__Segmentation__Fill_Label('156', '112')
Process.Stack__Segmentation__Fill_Label('87', '112')
Process.Stack__Segmentation__Fill_Label('8', '112')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('188', '0')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__Segmentation__Fill_Label('190', '15')
Process.Stack__Segmentation__Fill_Label('15', '15')
Process.Stack__Segmentation__Fill_Label('15', '15')
Process.Stack__Segmentation__Fill_Label('15', '15')
Process.Stack__Segmentation__Fill_Label('15', '15')
Process.Stack__Segmentation__Fill_Label('15', '15')
Process.Stack__Segmentation__Fill_Label('15', '15')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__System__Save('', 'No', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_2023_09_11__14_19_00_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Invert()
Process.Stack__Filters__Invert()
Process.Stack__Filters__Invert()
Process.Stack__Filters__Invert()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('2', '0')
Process.Stack__Segmentation__Fill_Label('180', '0')
Process.Stack__Segmentation__Fill_Label('122', '0')
Process.Stack__Segmentation__Fill_Label('68', '0')
Process.Stack__Segmentation__Fill_Label('190', '0')
Process.Stack__Segmentation__Fill_Label('54', '0')
Process.Stack__Segmentation__Fill_Label('80', '0')
Process.Stack__Segmentation__Fill_Label('142', '0')
Process.Stack__Segmentation__Fill_Label('77', '0')
Process.Stack__Segmentation__Fill_Label('86', '0')
Process.Stack__Segmentation__Fill_Label('189', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('217', '0')
Process.Stack__Segmentation__Fill_Label('185', '0')
Process.Stack__Segmentation__Fill_Label('208', '0')
Process.Stack__Segmentation__Fill_Label('140', '0')
Process.Stack__Segmentation__Fill_Label('89', '0')
Process.Stack__Segmentation__Fill_Label('126', '0')
Process.Stack__Segmentation__Fill_Label('8', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('71', '0')
Process.Stack__Segmentation__Fill_Label('53', '0')
Process.Stack__Segmentation__Fill_Label('96', '0')
Process.Stack__Segmentation__Fill_Label('175', '0')
Process.Stack__Segmentation__Fill_Label('9', '0')
Process.Stack__Segmentation__Fill_Label('13', '0')
Process.Stack__Segmentation__Fill_Label('95', '0')
Process.Stack__Segmentation__Fill_Label('64', '0')
Process.Stack__Segmentation__Fill_Label('27', '0')
Process.Stack__Segmentation__Fill_Label('123', '0')
Process.Stack__Segmentation__Fill_Label('40', '0')
Process.Stack__Segmentation__Fill_Label('202', '0')
Process.Stack__Segmentation__Fill_Label('36', '0')
Process.Stack__Segmentation__Fill_Label('49', '0')
Process.Stack__Segmentation__Fill_Label('92', '0')
Process.Stack__Segmentation__Fill_Label('193', '0')
Process.Stack__Segmentation__Fill_Label('143', '0')
Process.Stack__Segmentation__Fill_Label('41', '0')
Process.Stack__Segmentation__Fill_Label('5', '0')
Process.Stack__Segmentation__Fill_Label('214', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_mesh2.mgxm', 'no', 'no', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 10:03:13
Process.Misc__System__Save_View('')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_2/Ac_DA_3_2_2023_09_11__14_22_32_Out.tif', 'Main', '0', '')
Process.Mesh__System__Reset('-1')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('53', '0')
Process.Stack__Segmentation__Fill_Label('19', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('15', '0')
Process.Stack__Segmentation__Fill_Label('98', '0')
Process.Stack__Segmentation__Fill_Label('77', '0')
Process.Stack__Segmentation__Fill_Label('40', '0')
Process.Stack__Segmentation__Fill_Label('117', '0')
Process.Stack__Segmentation__Fill_Label('115', '0')
Process.Stack__Segmentation__Fill_Label('38', '0')
Process.Stack__Segmentation__Fill_Label('55', '0')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__Segmentation__Fill_Label('65', '0')
Process.Stack__Segmentation__Fill_Label('32', '0')
Process.Stack__Segmentation__Fill_Label('33', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('93', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('10', '0')
Process.Stack__Segmentation__Fill_Label('99', '0')
Process.Stack__Segmentation__Fill_Label('64', '0')
Process.Stack__Segmentation__Fill_Label('82', '0')
Process.Stack__Segmentation__Fill_Label('56', '0')
Process.Stack__Segmentation__Fill_Label('18', '0')
Process.Stack__Segmentation__Fill_Label('88', '0')
Process.Stack__Segmentation__Fill_Label('111', '0')
Process.Stack__Segmentation__Fill_Label('28', '0')
Process.Stack__Segmentation__Fill_Label('12', '0')
Process.Stack__Segmentation__Fill_Label('107', '0')
Process.Stack__Segmentation__Fill_Label('26', '0')
Process.Stack__Segmentation__Fill_Label('91', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('114', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_2/Ac_DA_3_2_2023_09_11__14_22_32_Out.tif', 'Work', '0', '')
Process.Stack__Segmentation__Fill_Label('74', '54')
Process.Stack__Segmentation__Fill_Label('4', '80')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_mesh2_final.mgxv')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 11:50:26
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_2023_09_11__14_19_00_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out.tif', 'Main', '0', '')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_mesh2_final.mgxv')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 14:27:58
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_mesh2_final.mgxv')
Process.Stack__Canvas__Change_Voxel_Size('1.0', '1.0', '1.0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_2023_09_11__14_19_00_Out.tif', 'Main', '0', '')
Process.Stack__Canvas__Change_Voxel_Size('0.207', '0.207', '0.3')
Process.Stack__Canvas__Change_Voxel_Size('0.3', '0.3', '0.3')
Process.Stack__Canvas__Change_Voxel_Size('0.1', '0.1', '0.3')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('3', '0')
Process.Stack__Segmentation__Fill_Label('2', '0')
Process.Stack__Segmentation__Fill_Label('6', '0')
Process.Stack__Segmentation__Fill_Label('1', '0')
Process.Stack__Segmentation__Fill_Label('5', '0')
Process.Stack__Segmentation__Fill_Label('8', '0')
Process.Mesh__System__Reset('-1')
Process.Stack__Canvas__Change_Voxel_Size('0.2', '0.2', '0.3')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_1/Ac_DA_3_1_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out.tif', 'Main', '0', '')
Process.Mesh__System__Reset('-1')
Process.Stack__Canvas__Change_Voxel_Size('0.2', '0.2', '0.3')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('7', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('15', '0')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
