######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 15:08:08

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '10.0', '10.0', '10.0')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('67', '0')
Process.Stack__Segmentation__Fill_Label('230', '0')
Process.Stack__Segmentation__Fill_Label('2', '0')
Process.Stack__Segmentation__Fill_Label('205', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('280', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__Segmentation__Fill_Label('224', '0')
Process.Stack__Segmentation__Fill_Label('192', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('151', '0')
Process.Stack__Segmentation__Fill_Label('303', '0')
Process.Stack__Segmentation__Fill_Label('129', '35')
Process.Stack__Segmentation__Fill_Label('282', '35')
Process.Stack__Segmentation__Fill_Label('314', '0')
Process.Stack__Segmentation__Fill_Label('313', '0')
Process.Stack__Segmentation__Fill_Label('311', '0')
Process.Stack__Segmentation__Fill_Label('312', '0')
Process.Stack__Segmentation__Fill_Label('310', '0')
Process.Stack__Segmentation__Fill_Label('305', '0')
Process.Stack__Segmentation__Fill_Label('306', '0')
Process.Stack__Segmentation__Fill_Label('307', '0')
Process.Stack__Segmentation__Fill_Label('309', '0')
Process.Stack__Segmentation__Fill_Label('308', '0')
Process.Stack__Segmentation__Fill_Label('201', '314')
Process.Stack__Segmentation__Fill_Label('139', '314')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 15:15:02
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-15 12:06:35
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_5/Ac_DA_1_5_mesh.mgxv')
Process.Mesh__System__Reset('-1')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Misc__System__Save_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_5/Ac_DA_1_5_mesh.mgxv')
