######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 15:15:29

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('27', '0')
Process.Stack__Segmentation__Fill_Label('172', '0')
Process.Stack__Segmentation__Fill_Label('5', '0')
Process.Stack__Segmentation__Fill_Label('14', '0')
Process.Stack__Segmentation__Fill_Label('164', '0')
Process.Stack__Segmentation__Fill_Label('124', '0')
Process.Stack__Segmentation__Fill_Label('210', '0')
Process.Stack__Segmentation__Fill_Label('67', '0')
Process.Stack__Segmentation__Fill_Label('101', '0')
Process.Stack__Segmentation__Fill_Label('123', '0')
Process.Stack__Segmentation__Fill_Label('30', '0')
Process.Stack__Segmentation__Fill_Label('75', '0')
Process.Stack__Segmentation__Fill_Label('156', '0')
Process.Stack__Segmentation__Fill_Label('148', '0')
Process.Stack__Segmentation__Fill_Label('200', '0')
Process.Stack__Segmentation__Fill_Label('3', '0')
Process.Stack__Segmentation__Fill_Label('213', '0')
Process.Stack__Segmentation__Fill_Label('184', '0')
Process.Stack__Segmentation__Fill_Label('197', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('214', '0')
Process.Stack__Segmentation__Fill_Label('121', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__Segmentation__Fill_Label('176', '0')
Process.Stack__Segmentation__Fill_Label('136', '0')
Process.Stack__Segmentation__Fill_Label('62', '0')
Process.Stack__Segmentation__Fill_Label('38', '0')
Process.Stack__Segmentation__Fill_Label('53', '0')
Process.Stack__Segmentation__Fill_Label('41', '0')
Process.Stack__Segmentation__Fill_Label('16', '0')
Process.Stack__Segmentation__Fill_Label('201', '0')
Process.Stack__Segmentation__Fill_Label('107', '0')
Process.Stack__Segmentation__Fill_Label('115', '0')
Process.Stack__Segmentation__Fill_Label('83', '0')
Process.Stack__Segmentation__Fill_Label('32', '0')
Process.Stack__Segmentation__Fill_Label('110', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('105', '0')
Process.Stack__Segmentation__Fill_Label('158', '0')
Process.Stack__Segmentation__Fill_Label('191', '0')
Process.Stack__Segmentation__Fill_Label('17', '0')
Process.Stack__Segmentation__Fill_Label('174', '0')
Process.Stack__Segmentation__Fill_Label('8', '0')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__Segmentation__Fill_Label('21', '61')
Process.Stack__Segmentation__Fill_Label('142', '61')
Process.Stack__Segmentation__Fill_Label('133', '78')
Process.Stack__Segmentation__Fill_Label('61', '12')
Process.Stack__Segmentation__Fill_Label('154', '12')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 15:21:55
Process.Misc__System__Save_View('')
