######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 10:16:19

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('177', '0')
Process.Stack__Segmentation__Fill_Label('179', '0')
Process.Stack__Segmentation__Fill_Label('25', '0')
Process.Stack__Segmentation__Fill_Label('59', '0')
Process.Stack__Segmentation__Fill_Label('198', '0')
Process.Stack__Segmentation__Fill_Label('192', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('62', '0')
Process.Stack__Segmentation__Fill_Label('147', '0')
Process.Stack__Segmentation__Fill_Label('149', '0')
Process.Stack__Segmentation__Fill_Label('28', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('4', '0')
Process.Stack__Segmentation__Fill_Label('34', '0')
Process.Stack__Segmentation__Fill_Label('23', '0')
Process.Stack__Segmentation__Fill_Label('32', '0')
Process.Stack__Segmentation__Fill_Label('131', '0')
Process.Stack__Segmentation__Fill_Label('120', '0')
Process.Stack__Segmentation__Fill_Label('86', '0')
Process.Stack__Segmentation__Fill_Label('182', '0')
Process.Stack__Segmentation__Fill_Label('43', '0')
Process.Stack__Segmentation__Fill_Label('19', '0')
Process.Stack__Segmentation__Fill_Label('125', '0')
Process.Stack__Segmentation__Fill_Label('81', '0')
Process.Stack__Segmentation__Fill_Label('8', '0')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Stack__Segmentation__Fill_Label('70', '0')
Process.Stack__Segmentation__Fill_Label('74', '0')
Process.Stack__Segmentation__Fill_Label('193', '0')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__Segmentation__Fill_Label('160', '0')
Process.Stack__Segmentation__Fill_Label('168', '0')
Process.Stack__Segmentation__Fill_Label('144', '18')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_4/Ac_DA_3_4_2023_09_11__14_27_38_Out.tif', 'Work', '0', '')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 10:21:28
Process.Misc__System__Save_View('')
