######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 15:59:25
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '10.0', '10.0', '10.0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('76', '0')
Process.Stack__Segmentation__Fill_Label('205', '0')
Process.Stack__Segmentation__Fill_Label('139', '0')
Process.Stack__Segmentation__Fill_Label('35', '0')
Process.Stack__Segmentation__Fill_Label('121', '0')
Process.Stack__Segmentation__Fill_Label('101', '0')
Process.Stack__Segmentation__Fill_Label('227', '0')
Process.Stack__Segmentation__Fill_Label('200', '0')
Process.Stack__Segmentation__Fill_Label('249', '0')
Process.Stack__Segmentation__Fill_Label('60', '0')
Process.Stack__Segmentation__Fill_Label('34', '0')
Process.Stack__Segmentation__Fill_Label('188', '0')
Process.Stack__Segmentation__Fill_Label('174', '0')
Process.Stack__Segmentation__Fill_Label('242', '0')
Process.Stack__Segmentation__Fill_Label('209', '0')
Process.Stack__Segmentation__Fill_Label('150', '0')
Process.Stack__Segmentation__Fill_Label('105', '0')
Process.Stack__Segmentation__Fill_Label('51', '0')
Process.Stack__Segmentation__Fill_Label('94', '0')
Process.Stack__Segmentation__Fill_Label('27', '0')
Process.Stack__Segmentation__Fill_Label('13', '0')
Process.Stack__Segmentation__Fill_Label('47', '0')
Process.Stack__Segmentation__Fill_Label('61', '0')
Process.Stack__Segmentation__Fill_Label('198', '0')
Process.Stack__Segmentation__Fill_Label('72', '0')
Process.Stack__Segmentation__Fill_Label('164', '0')
Process.Stack__Segmentation__Fill_Label('187', '0')
Process.Stack__Segmentation__Fill_Label('148', '0')
Process.Stack__Segmentation__Fill_Label('17', '0')
Process.Stack__Segmentation__Fill_Label('43', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('106', '0')
Process.Stack__Segmentation__Fill_Label('235', '0')
Process.Stack__Segmentation__Fill_Label('189', '0')
Process.Stack__Segmentation__Fill_Label('33', '0')
Process.Stack__Segmentation__Fill_Label('231', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('65', '0')
Process.Stack__Segmentation__Fill_Label('146', '0')
Process.Stack__Segmentation__Fill_Label('77', '0')
Process.Stack__Segmentation__Fill_Label('25', '0')
Process.Stack__Segmentation__Fill_Label('91', '0')
Process.Stack__Segmentation__Fill_Label('68', '0')
Process.Stack__Segmentation__Fill_Label('194', '0')
Process.Stack__Segmentation__Fill_Label('167', '0')
Process.Stack__Segmentation__Fill_Label('260', '0')
Process.Stack__Segmentation__Fill_Label('170', '0')
Process.Stack__Segmentation__Fill_Label('135', '0')
Process.Stack__Segmentation__Fill_Label('254', '0')
Process.Stack__Segmentation__Fill_Label('66', '0')
Process.Stack__Segmentation__Fill_Label('172', '0')
Process.Stack__Segmentation__Fill_Label('69', '0')
Process.Stack__Segmentation__Fill_Label('97', '0')
Process.Stack__Segmentation__Fill_Label('55', '0')
Process.Stack__Segmentation__Fill_Label('110', '0')
Process.Stack__Segmentation__Fill_Label('234', '0')
Process.Stack__Segmentation__Fill_Label('193', '0')
Process.Stack__Segmentation__Fill_Label('130', '0')
Process.Stack__Segmentation__Fill_Label('159', '0')
Process.Stack__Segmentation__Fill_Label('22', '0')
Process.Stack__Segmentation__Fill_Label('134', '0')
Process.Stack__Segmentation__Fill_Label('229', '0')
Process.Stack__Segmentation__Fill_Label('31', '0')
Process.Stack__Segmentation__Fill_Label('252', '0')
Process.Stack__Segmentation__Fill_Label('213', '0')
Process.Stack__Segmentation__Fill_Label('128', '0')
Process.Stack__Segmentation__Fill_Label('184', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('179', '0')
Process.Stack__Segmentation__Fill_Label('232', '0')
Process.Stack__Segmentation__Fill_Label('87', '0')
Process.Stack__Segmentation__Fill_Label('226', '0')
Process.Stack__Segmentation__Fill_Label('185', '0')
Process.Stack__Segmentation__Fill_Label('49', '0')
Process.Stack__Segmentation__Fill_Label('223', '0')
Process.Stack__Segmentation__Fill_Label('79', '0')
Process.Stack__Segmentation__Fill_Label('204', '0')
Process.Stack__Segmentation__Fill_Label('136', '0')
Process.Stack__Segmentation__Fill_Label('108', '120')
Process.Stack__Segmentation__Fill_Label('57', '120')
Process.Stack__Segmentation__Fill_Label('14', '0')
Process.Stack__Segmentation__Fill_Label('1', '0')
Process.Stack__Segmentation__Fill_Label('120', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_2023_09_11__13_53_21_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 11:37:43

######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 13:47:52

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('16.0')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('156', '0')
Process.Stack__Segmentation__Fill_Label('98', '0')
Process.Stack__Segmentation__Fill_Label('67', '0')
Process.Stack__Segmentation__Fill_Label('23', '0')
Process.Stack__Segmentation__Fill_Label('146', '0')
Process.Stack__Segmentation__Fill_Label('74', '0')
Process.Stack__Segmentation__Fill_Label('203', '0')
Process.Stack__Segmentation__Fill_Label('176', '0')
Process.Stack__Segmentation__Fill_Label('118', '0')
Process.Stack__Segmentation__Fill_Label('43', '0')
Process.Stack__Segmentation__Fill_Label('6', '0')
Process.Stack__Segmentation__Fill_Label('173', '0')
Process.Stack__Segmentation__Fill_Label('65', '0')
Process.Stack__Segmentation__Fill_Label('226', '0')
Process.Stack__Segmentation__Fill_Label('101', '0')
Process.Stack__Segmentation__Fill_Label('111', '0')
Process.Stack__Segmentation__Fill_Label('108', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('157', '0')
Process.Stack__Segmentation__Fill_Label('49', '0')
Process.Stack__Segmentation__Fill_Label('129', '0')
Process.Stack__Segmentation__Fill_Label('137', '0')
Process.Stack__Segmentation__Fill_Label('46', '0')
Process.Stack__Segmentation__Fill_Label('1', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('210', '0')
Process.Stack__Segmentation__Fill_Label('4', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__Segmentation__Fill_Label('207', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('19', '0')
Process.Stack__Segmentation__Fill_Label('21', '0')
Process.Stack__Segmentation__Fill_Label('49', '0')
Process.Stack__Segmentation__Fill_Label('24', '0')
Process.Stack__Segmentation__Fill_Label('15', '0')
Process.Stack__Segmentation__Fill_Label('13', '0')
Process.Stack__Segmentation__Fill_Label('132', '0')
Process.Stack__Segmentation__Fill_Label('36', '0')
Process.Stack__Segmentation__Fill_Label('71', '0')
Process.Stack__Segmentation__Fill_Label('59', '0')
Process.Stack__Segmentation__Fill_Label('149', '0')
Process.Stack__Segmentation__Fill_Label('44', '0')
Process.Stack__Segmentation__Fill_Label('53', '0')
Process.Stack__Segmentation__Fill_Label('143', '0')
Process.Stack__Segmentation__Fill_Label('156', '0')
Process.Stack__Segmentation__Fill_Label('12', '0')
Process.Stack__Segmentation__Fill_Label('38', '0')
Process.Stack__Segmentation__Fill_Label('46', '0')
Process.Stack__Segmentation__Fill_Label('6', '0')
Process.Stack__Segmentation__Fill_Label('7', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('120', '0')
Process.Stack__Segmentation__Fill_Label('104', '0')
Process.Stack__Segmentation__Fill_Label('129', '0')
Process.Stack__Segmentation__Fill_Label('123', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('133', '0')
Process.Stack__Segmentation__Fill_Label('66', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('105', '0')
Process.Stack__Segmentation__Fill_Label('125', '0')
Process.Stack__Segmentation__Fill_Label('174', '0')
Process.Stack__Segmentation__Fill_Label('93', '0')
Process.Stack__Segmentation__Fill_Label('73', '0')
Process.Stack__Segmentation__Fill_Label('115', '0')
Process.Stack__Segmentation__Fill_Label('31', '0')
Process.Stack__Segmentation__Fill_Label('30', '0')
Process.Stack__Segmentation__Fill_Label('102', '0')
Process.Stack__Segmentation__Fill_Label('83', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('106', '0')
Process.Stack__Segmentation__Fill_Label('4', '0')
Process.Stack__Segmentation__Fill_Label('43', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__Segmentation__Fill_Label('107', '0')
Process.Stack__Segmentation__Fill_Label('18', '0')
Process.Stack__Segmentation__Fill_Label('76', '0')
Process.Stack__Segmentation__Fill_Label('142', '0')
Process.Stack__Segmentation__Fill_Label('108', '0')
Process.Stack__Segmentation__Fill_Label('91', '0')
Process.Stack__Segmentation__Fill_Label('88', '0')
Process.Stack__Segmentation__Fill_Label('5', '0')
Process.Stack__Segmentation__Fill_Label('112', '0')
Process.Stack__Segmentation__Fill_Label('80', '0')
Process.Stack__Segmentation__Fill_Label('64', '0')
Process.Stack__Segmentation__Fill_Label('152', '0')
Process.Stack__Segmentation__Fill_Label('126', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('99', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('175', '0')
Process.Stack__Segmentation__Fill_Label('3', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Stack__Segmentation__Fill_Label('150', '92')
Process.Stack__Segmentation__Fill_Label('95', '0')
Process.Stack__Segmentation__Fill_Label('55', '0')
Process.Stack__Segmentation__Fill_Label('74', '45')
Process.Stack__Segmentation__Fill_Label('92', '45')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 13:55:47
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 11:35:10
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 11:35:24

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN.tif', 'Main', '0', '')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('248', '0')
Process.Stack__Segmentation__Fill_Label('313', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN.tif', 'Work', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN.tif', 'Work', '0', '')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('242', '0')
Process.Stack__Segmentation__Fill_Label('369', '0')
Process.Stack__Segmentation__Fill_Label('95', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN.tif', 'Work', '0', '')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('58', '0')
Process.Stack__Segmentation__Fill_Label('25', '0')
Process.Stack__Segmentation__Fill_Label('52', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('12', '0')
Process.Stack__Segmentation__Fill_Label('335', '0')
Process.Stack__Segmentation__Fill_Label('129', '0')
Process.Stack__Segmentation__Fill_Label('166', '0')
Process.Stack__Segmentation__Fill_Label('58', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_2023_09_11__13_53_21_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 12:47:06
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Mesh__System__Reset('-1')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh.mgxm', 'no', 'no', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('541', '0')
Process.Stack__Segmentation__Fill_Label('195', '0')
Process.Stack__Segmentation__Fill_Label('303', '0')
Process.Stack__Segmentation__Fill_Label('623', '0')
Process.Stack__Segmentation__Fill_Label('32', '0')
Process.Stack__Segmentation__Fill_Label('76', '0')
Process.Stack__Segmentation__Fill_Label('167', '0')
Process.Stack__Segmentation__Fill_Label('502', '0')
Process.Stack__Segmentation__Fill_Label('408', '0')
Process.Stack__Segmentation__Fill_Label('341', '0')
Process.Stack__Segmentation__Fill_Label('638', '0')
Process.Stack__Segmentation__Fill_Label('3', '0')
Process.Stack__Segmentation__Fill_Label('85', '0')
Process.Stack__Segmentation__Fill_Label('304', '0')
Process.Stack__Segmentation__Fill_Label('653', '0')
Process.Stack__Segmentation__Fill_Label('151', '0')
Process.Stack__Segmentation__Fill_Label('440', '0')
Process.Stack__Segmentation__Fill_Label('159', '0')
Process.Stack__Segmentation__Fill_Label('461', '0')
Process.Stack__Segmentation__Fill_Label('450', '0')
Process.Stack__Segmentation__Fill_Label('367', '0')
Process.Stack__Segmentation__Fill_Label('293', '0')
Process.Stack__Segmentation__Fill_Label('464', '0')
Process.Stack__Segmentation__Fill_Label('225', '0')
Process.Stack__Segmentation__Fill_Label('80', '0')
Process.Stack__Segmentation__Fill_Label('2', '0')
Process.Stack__Segmentation__Fill_Label('671', '0')
Process.Stack__Segmentation__Fill_Label('6', '0')
Process.Stack__Segmentation__Fill_Label('169', '0')
Process.Stack__Segmentation__Fill_Label('61', '0')
Process.Stack__Segmentation__Fill_Label('677', '0')
Process.Stack__Segmentation__Fill_Label('392', '0')
Process.Stack__Segmentation__Fill_Label('43', '0')
Process.Stack__Segmentation__Fill_Label('394', '0')
Process.Stack__Segmentation__Fill_Label('97', '0')
Process.Stack__Segmentation__Fill_Label('336', '0')
Process.Stack__Segmentation__Fill_Label('313', '0')
Process.Stack__Segmentation__Fill_Label('201', '0')
Process.Stack__Segmentation__Fill_Label('60', '0')
Process.Stack__Segmentation__Fill_Label('5', '0')
Process.Stack__Segmentation__Fill_Label('667', '0')
Process.Stack__Segmentation__Fill_Label('581', '0')
Process.Stack__Segmentation__Fill_Label('413', '0')
Process.Stack__Segmentation__Fill_Label('36', '0')
Process.Stack__Segmentation__Fill_Label('376', '0')
Process.Stack__Segmentation__Fill_Label('639', '0')
Process.Stack__Segmentation__Fill_Label('357', '0')
Process.Stack__Segmentation__Fill_Label('476', '0')
Process.Stack__Segmentation__Fill_Label('482', '0')
Process.Stack__Segmentation__Fill_Label('720', '0')
Process.Stack__Segmentation__Fill_Label('202', '0')
Process.Stack__Segmentation__Fill_Label('584', '0')
Process.Stack__Segmentation__Fill_Label('649', '0')
Process.Stack__Segmentation__Fill_Label('15', '0')
Process.Stack__Segmentation__Fill_Label('454', '0')
Process.Stack__Segmentation__Fill_Label('298', '0')
Process.Stack__Segmentation__Fill_Label('455', '0')
Process.Stack__Segmentation__Fill_Label('149', '0')
Process.Stack__Segmentation__Fill_Label('209', '0')
Process.Stack__Segmentation__Fill_Label('305', '0')
Process.Stack__Segmentation__Fill_Label('551', '0')
Process.Stack__Segmentation__Fill_Label('473', '0')
Process.Stack__Segmentation__Fill_Label('543', '0')
Process.Stack__Segmentation__Fill_Label('50', '0')
Process.Stack__Segmentation__Fill_Label('82', '0')
Process.Stack__Segmentation__Fill_Label('592', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('179', '0')
Process.Stack__Segmentation__Fill_Label('27', '0')
Process.Stack__Segmentation__Fill_Label('266', '0')
Process.Stack__Segmentation__Fill_Label('629', '0')
Process.Stack__Segmentation__Fill_Label('262', '0')
Process.Stack__Segmentation__Fill_Label('383', '0')
Process.Stack__Segmentation__Fill_Label('379', '0')
Process.Stack__Segmentation__Fill_Label('96', '0')
Process.Stack__Segmentation__Fill_Label('521', '0')
Process.Stack__Segmentation__Fill_Label('658', '0')
Process.Stack__Segmentation__Fill_Label('628', '0')
Process.Stack__Segmentation__Fill_Label('344', '0')
Process.Stack__Segmentation__Fill_Label('328', '0')
Process.Stack__Segmentation__Fill_Label('272', '0')
Process.Stack__Segmentation__Fill_Label('152', '0')
Process.Stack__Segmentation__Fill_Label('385', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN_seg.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN_seg.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN2.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_CNN_seg.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('111', '0')
Process.Stack__Segmentation__Fill_Label('55', '0')
Process.Stack__Segmentation__Fill_Label('31', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('171', '0')
Process.Stack__Segmentation__Fill_Label('159', '0')
Process.Stack__Segmentation__Fill_Label('187', '0')
Process.Stack__Segmentation__Fill_Label('49', '0')
Process.Stack__Segmentation__Fill_Label('139', '0')
Process.Stack__Segmentation__Fill_Label('224', '0')
Process.Stack__Segmentation__Fill_Label('125', '0')
Process.Stack__Segmentation__Fill_Label('58', '0')
Process.Stack__Segmentation__Fill_Label('223', '0')
Process.Stack__Segmentation__Fill_Label('140', '0')
Process.Stack__Segmentation__Fill_Label('226', '0')
Process.Stack__Segmentation__Fill_Label('143', '0')
Process.Stack__Segmentation__Fill_Label('8', '0')
Process.Stack__Segmentation__Fill_Label('204', '0')
Process.Stack__Segmentation__Fill_Label('15', '0')
Process.Stack__Segmentation__Fill_Label('175', '0')
Process.Stack__Segmentation__Fill_Label('182', '0')
Process.Stack__Segmentation__Fill_Label('227', '0')
Process.Stack__Segmentation__Fill_Label('148', '0')
Process.Stack__Segmentation__Fill_Label('121', '0')
Process.Stack__Segmentation__Fill_Label('173', '0')
Process.Stack__Segmentation__Fill_Label('165', '0')
Process.Stack__Segmentation__Fill_Label('51', '0')
Process.Stack__Segmentation__Fill_Label('228', '0')
Process.Stack__Segmentation__Fill_Label('12', '0')
Process.Stack__Segmentation__Fill_Label('59', '0')
Process.Stack__Segmentation__Fill_Label('3', '0')
Process.Stack__Segmentation__Fill_Label('89', '0')
Process.Stack__Segmentation__Fill_Label('33', '0')
Process.Stack__Segmentation__Fill_Label('221', '0')
Process.Stack__Segmentation__Fill_Label('168', '0')
Process.Stack__Segmentation__Fill_Label('105', '0')
Process.Stack__Segmentation__Fill_Label('198', '0')
Process.Stack__Segmentation__Fill_Label('18', '0')
Process.Stack__Segmentation__Fill_Label('55', '0')
Process.Stack__Segmentation__Fill_Label('207', '0')
Process.Stack__Segmentation__Fill_Label('155', '0')
Process.Stack__Segmentation__Fill_Label('233', '0')
Process.Stack__Segmentation__Fill_Label('79', '0')
Process.Stack__Segmentation__Fill_Label('249', '0')
Process.Stack__Segmentation__Fill_Label('95', '0')
Process.Stack__Segmentation__Fill_Label('157', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('54', '0')
Process.Stack__Segmentation__Fill_Label('23', '0')
Process.Stack__Segmentation__Fill_Label('243', '0')
Process.Stack__Segmentation__Fill_Label('50', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('136', '0')
Process.Stack__Segmentation__Fill_Label('1', '0')
Process.Stack__Segmentation__Fill_Label('176', '0')
Process.Stack__Segmentation__Fill_Label('214', '0')
Process.Stack__Segmentation__Fill_Label('81', '0')
Process.Stack__Segmentation__Fill_Label('103', '0')
Process.Stack__Segmentation__Fill_Label('122', '0')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__Segmentation__Fill_Label('217', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('97', '0')
Process.Stack__Segmentation__Fill_Label('216', '0')
Process.Stack__Segmentation__Fill_Label('99', '0')
Process.Stack__Segmentation__Fill_Label('20', '0')
Process.Stack__Segmentation__Fill_Label('22', '0')
Process.Stack__Segmentation__Fill_Label('135', '0')
Process.Stack__Segmentation__Fill_Label('56', '0')
Process.Stack__Segmentation__Fill_Label('25', '0')
Process.Stack__Segmentation__Fill_Label('222', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('261', '0')
Process.Stack__Segmentation__Fill_Label('208', '57')
Process.Stack__Segmentation__Fill_Label('131', '57')
Process.Stack__Segmentation__Fill_Label('57', '57')
Process.Stack__Segmentation__Fill_Label('53', '57')
Process.Stack__Segmentation__Fill_Label('210', '57')
Process.Stack__Segmentation__Fill_Label('212', '85')
Process.Stack__Segmentation__Fill_Label('154', '85')
Process.Stack__Segmentation__Fill_Label('150', '85')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh2.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh2.mgxm', 'no', 'no', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_2023_09_11__13_46_20_Out_gamma.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '1.5', '1.5', '1.5')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '5', '5', '5')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('434', '0')
Process.Stack__Segmentation__Fill_Label('430', '0')
Process.Stack__Segmentation__Fill_Label('206', '0')
Process.Stack__Segmentation__Fill_Label('47', '0')
Process.Stack__Segmentation__Fill_Label('287', '0')
Process.Stack__Segmentation__Fill_Label('32', '0')
Process.Stack__Segmentation__Fill_Label('13', '0')
Process.Stack__Segmentation__Fill_Label('263', '0')
Process.Stack__Segmentation__Fill_Label('201', '0')
Process.Stack__Segmentation__Fill_Label('265', '0')
Process.Misc__System__Load_View('')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh2.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_mesh.mgxm', 'no', 'no', '0')
Process.Misc__System__Load_View('')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh2.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 14:44:11
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 14:44:16
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 14:44:43
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_2/Ac_DA_1_2_final.mgxv')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-06 16:19:06
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_final.mgxv')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_1/Ac_DA_2_1_mesh2.mgxm', 'no', 'no', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_7/Ac_DA_3_7_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
