######## New MorphoDynamX session v2.0 r2-1582: 2025-03-20 14:31:08
Process.Tools__System__Save_View('/home/tomkinsm/.vlab/tmp/VLYUy1So/AirMattress.mdxv')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Air_Mattress__05_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__Air_Mattress__06_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__Air_Mattress__07_Set_Material_Properties('', '', '40', '40', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__Air_Mattress__08_Set_Pressure('', '', '1', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Air_Mattress__01_FEM_Membranes('', '', '10', '0.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/Air Mattress/06 StressStrain', 'snapshot', 'Model/Air Mattress/02 Triangle Derivs', 'Model/Air Mattress/03 Pressure Derivs', 'Model/Air Mattress/04 Dirichlet Derivs')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D Separated')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__Air_Mattress__05_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__Air_Mattress__06_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__Air_Mattress__07_Set_Material_Properties('', '', '40', '40', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__Air_Mattress__08_Set_Pressure('', '', '1', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Air_Mattress__01_FEM_Membranes('', '', '10', '0.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/Air Mattress/06 StressStrain', 'snapshot', 'Model/Air Mattress/02 Triangle Derivs', 'Model/Air Mattress/03 Pressure Derivs', 'Model/Air Mattress/04 Dirichlet Derivs')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D Separated')
Process.Mesh__System__Save('', '', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Mesh__System__Save('', '', 'No')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Air_Mattress__05_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__Air_Mattress__06_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__Air_Mattress__07_Set_Material_Properties('', '', '40', '40', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__Air_Mattress__08_Set_Pressure('', '', '1', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Air_Mattress__01_FEM_Membranes('', '', '10', '0.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/Air Mattress/06 StressStrain', 'snapshot', 'Model/Air Mattress/02 Triangle Derivs', 'Model/Air Mattress/03 Pressure Derivs', 'Model/Air Mattress/04 Dirichlet Derivs')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D Separated')
Process.Mesh__System__Save('', '', 'No')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Air_Mattress__05_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__Air_Mattress__06_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__Air_Mattress__07_Set_Material_Properties('', '', '40', '40', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__Air_Mattress__08_Set_Pressure('', '', '1', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Air_Mattress__01_FEM_Membranes('', '', '10', '0.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/Air Mattress/06 StressStrain', '', 'Model/Air Mattress/02 Triangle Derivs', 'Model/Air Mattress/03 Pressure Derivs', 'Model/Air Mattress/04 Dirichlet Derivs')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D 3D')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D Separated')
Process.Mesh__System__Save('', '', 'No')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Air_Mattress__05_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__Air_Mattress__06_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__Air_Mattress__07_Set_Material_Properties('', '', '40', '40', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__Air_Mattress__08_Set_Pressure('', '', '1', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Air_Mattress__01_FEM_Membranes('', '', '10', '0.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/Air Mattress/06 StressStrain', '', 'Model/Air Mattress/02 Triangle Derivs', 'Model/Air Mattress/03 Pressure Derivs', 'Model/Air Mattress/04 Dirichlet Derivs')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D Separated')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D')
Process.Mesh__System__Save('', '', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__Air_Mattress__05_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__Air_Mattress__06_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__Air_Mattress__07_Set_Material_Properties('', '', '40', '40', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__Air_Mattress__08_Set_Pressure('', '', '1', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Air_Mattress__01_FEM_Membranes('', '', '10', '0.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/Air Mattress/06 StressStrain', '', 'Model/Air Mattress/02 Triangle Derivs', 'Model/Air Mattress/03 Pressure Derivs', 'Model/Air Mattress/04 Dirichlet Derivs')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__System__Save('', '', 'No')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D Separated')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D')
Process.Mesh__System__Save('', '', 'No')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Air_Mattress__05_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__Air_Mattress__06_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__Air_Mattress__07_Set_Material_Properties('', '', '40', '40', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__Air_Mattress__08_Set_Pressure('', '', '1', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Air_Mattress__01_FEM_Membranes('', '', '10', '0.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/Air Mattress/06 StressStrain', '', 'Model/Air Mattress/02 Triangle Derivs', 'Model/Air Mattress/03 Pressure Derivs', 'Model/Air Mattress/04 Dirichlet Derivs')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Position__Scale_Mesh('1.0', '1.0', '1.55')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', '', 'No', 'No')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Mesh__Position__Smooth_Mesh('10', 'No')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Combine_3D_Cells('', '', '', '1e-6')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D')
Process.Mesh__System__Delete_Cell_Complex('Stack1', 'MeshMGXM 3D Separated')
Process.Mesh__System__Save('', '', 'No')
Process.Model__Air_Mattress__10_Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
