######## New MorphoGraphX session v2.0 r1-189: 2023-10-02 16:19:32

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '10.0', '10.0', '10.0')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('174', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '0.5', '0.5', '0.5')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('539', '0')
Process.Stack__Segmentation__Fill_Label('961', '0')
Process.Stack__Segmentation__Fill_Label('859', '0')
Process.Stack__Segmentation__Fill_Label('316', '0')
Process.Stack__Segmentation__Fill_Label('689', '0')
Process.Stack__Segmentation__Fill_Label('781', '0')
Process.Stack__Segmentation__Fill_Label('783', '0')
Process.Stack__Segmentation__Fill_Label('104', '0')
Process.Stack__Segmentation__Fill_Label('784', '0')
Process.Stack__Segmentation__Fill_Label('540', '0')
Process.Stack__Segmentation__Fill_Label('837', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('766', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('576', '0')
Process.Stack__Segmentation__Fill_Label('84', '0')
Process.Stack__Segmentation__Fill_Label('461', '0')
Process.Stack__Segmentation__Fill_Label('527', '0')
Process.Stack__Segmentation__Fill_Label('1031', '0')
Process.Stack__Segmentation__Fill_Label('819', '0')
Process.Stack__Segmentation__Fill_Label('47', '0')
Process.Stack__Segmentation__Fill_Label('365', '0')
Process.Stack__Segmentation__Fill_Label('809', '0')
Process.Stack__Segmentation__Fill_Label('479', '0')
Process.Stack__Segmentation__Fill_Label('502', '0')
Process.Stack__Segmentation__Fill_Label('577', '0')
Process.Stack__Segmentation__Fill_Label('807', '0')
Process.Stack__Segmentation__Fill_Label('960', '0')
Process.Stack__Segmentation__Fill_Label('867', '0')
Process.Stack__Segmentation__Fill_Label('91', '0')
Process.Stack__Segmentation__Fill_Label('552', '0')
Process.Stack__Segmentation__Fill_Label('844', '0')
Process.Stack__Segmentation__Fill_Label('776', '0')
Process.Stack__Segmentation__Fill_Label('568', '0')
Process.Stack__Segmentation__Fill_Label('308', '0')
Process.Stack__Segmentation__Fill_Label('711', '0')
Process.Stack__Segmentation__Fill_Label('292', '0')
Process.Stack__Segmentation__Fill_Label('920', '0')
Process.Stack__Segmentation__Fill_Label('529', '0')
Process.Stack__Segmentation__Fill_Label('409', '0')
Process.Stack__Segmentation__Fill_Label('696', '0')
Process.Stack__Segmentation__Fill_Label('926', '0')
Process.Stack__Segmentation__Fill_Label('615', '0')
Process.Stack__Segmentation__Fill_Label('645', '0')
Process.Stack__Segmentation__Fill_Label('546', '0')
Process.Stack__Segmentation__Fill_Label('847', '0')
Process.Stack__Segmentation__Fill_Label('617', '0')
Process.Stack__Segmentation__Fill_Label('31', '0')
Process.Stack__Segmentation__Fill_Label('370', '0')
Process.Stack__Segmentation__Fill_Label('917', '0')
Process.Stack__Segmentation__Fill_Label('106', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('933', '0')
Process.Stack__Segmentation__Fill_Label('604', '0')
Process.Stack__Segmentation__Fill_Label('194', '0')
Process.Stack__Segmentation__Fill_Label('965', '0')
Process.Stack__Segmentation__Fill_Label('36', '0')
Process.Stack__Segmentation__Fill_Label('621', '0')
Process.Stack__Segmentation__Fill_Label('278', '0')
Process.Stack__Segmentation__Fill_Label('843', '0')
Process.Stack__Segmentation__Fill_Label('305', '0')
Process.Stack__Segmentation__Fill_Label('894', '0')
Process.Stack__Segmentation__Fill_Label('304', '0')
Process.Stack__Segmentation__Fill_Label('758', '0')
Process.Stack__Segmentation__Fill_Label('132', '0')
Process.Stack__Segmentation__Fill_Label('764', '0')
Process.Stack__Segmentation__Fill_Label('404', '0')
Process.Stack__Segmentation__Fill_Label('280', '0')
Process.Stack__Segmentation__Fill_Label('486', '0')
Process.Stack__Segmentation__Fill_Label('970', '0')
Process.Stack__Segmentation__Fill_Label('599', '0')
Process.Stack__Segmentation__Fill_Label('512', '0')
Process.Stack__Segmentation__Fill_Label('972', '0')
Process.Stack__Segmentation__Fill_Label('121', '0')
Process.Stack__Segmentation__Fill_Label('865', '0')
Process.Stack__Segmentation__Fill_Label('17', '0')
Process.Stack__Segmentation__Fill_Label('916', '0')
Process.Stack__Segmentation__Fill_Label('339', '0')
Process.Stack__Segmentation__Fill_Label('77', '0')
Process.Stack__Segmentation__Fill_Label('322', '0')
Process.Stack__Segmentation__Fill_Label('286', '0')
Process.Stack__Segmentation__Fill_Label('537', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('583', '7')
Process.Stack__Segmentation__Fill_Label('443', '7')
Process.Stack__Segmentation__Fill_Label('233', '7')
Process.Stack__Segmentation__Fill_Label('395', '7')
Process.Stack__Segmentation__Fill_Label('763', '7')
Process.Stack__Segmentation__Fill_Label('468', '7')
Process.Stack__Segmentation__Fill_Label('8', '7')
Process.Stack__Segmentation__Fill_Label('7', '7')
Process.Stack__Segmentation__Fill_Label('193', '7')
Process.Stack__Segmentation__Fill_Label('7', '7')
Process.Stack__Segmentation__Fill_Label('116', '7')
Process.Stack__Segmentation__Fill_Label('431', '7')
Process.Stack__Segmentation__Fill_Label('112', '7')
Process.Stack__Segmentation__Fill_Label('811', '7')
Process.Stack__Segmentation__Fill_Label('350', '7')
Process.Stack__Segmentation__Fill_Label('463', '7')
Process.Stack__Segmentation__Fill_Label('131', '7')
Process.Stack__Segmentation__Fill_Label('883', '7')
Process.Stack__Segmentation__Fill_Label('298', '7')
Process.Stack__Segmentation__Fill_Label('452', '0')
Process.Stack__Segmentation__Fill_Label('185', '42')
Process.Stack__Segmentation__Fill_Label('321', '42')
Process.Stack__Segmentation__Fill_Label('272', '42')
Process.Stack__Segmentation__Fill_Label('432', '42')
Process.Stack__Segmentation__Fill_Label('656', '42')
Process.Stack__Segmentation__Fill_Label('97', '42')
Process.Stack__Segmentation__Fill_Label('360', '42')
Process.Stack__Segmentation__Fill_Label('42', '49')
Process.Stack__Segmentation__Fill_Label('49', '49')
Process.Stack__Segmentation__Fill_Label('334', '49')
Process.Stack__Segmentation__Fill_Label('794', '49')
Process.Stack__Segmentation__Fill_Label('861', '49')
Process.Stack__Segmentation__Fill_Label('460', '49')
Process.Stack__Segmentation__Fill_Label('76', '49')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('418', '0')
Process.Stack__Segmentation__Fill_Label('932', '0')
Process.Stack__Segmentation__Fill_Label('841', '0')
Process.Stack__Segmentation__Fill_Label('995', '0')
Process.Stack__Segmentation__Fill_Label('914', '0')
Process.Stack__Segmentation__Fill_Label('92', '0')
Process.Stack__Segmentation__Fill_Label('307', '0')
Process.Stack__Segmentation__Fill_Label('216', '0')
Process.Stack__Segmentation__Fill_Label('1009', '0')
Process.Stack__Segmentation__Fill_Label('287', '0')
Process.Stack__Segmentation__Fill_Label('387', '0')
Process.Stack__Segmentation__Fill_Label('405', '0')
Process.Stack__Segmentation__Fill_Label('331', '0')
Process.Stack__Segmentation__Fill_Label('61', '0')
Process.Stack__Segmentation__Fill_Label('149', '0')
Process.Stack__Segmentation__Fill_Label('684', '0')
Process.Stack__Segmentation__Fill_Label('417', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_6/Ac_DA_2_6_2023_09_11__14_02_09_Out.tif', 'Work', '0', '')
Process.Stack__Segmentation__Fill_Label('149', '0')
Process.Stack__Segmentation__Fill_Label('368', '0')
Process.Stack__Segmentation__Fill_Label('279', '0')
Process.Stack__Segmentation__Fill_Label('387', '0')
Process.Stack__Segmentation__Fill_Label('331', '0')
Process.Stack__Segmentation__Fill_Label('307', '0')
Process.Stack__Segmentation__Fill_Label('640', '0')
Process.Stack__Segmentation__Fill_Label('906', '0')
Process.Stack__Segmentation__Fill_Label('323', '0')
Process.Stack__Segmentation__Fill_Label('405', '0')
Process.Stack__Segmentation__Fill_Label('374', '0')
Process.Stack__Segmentation__Fill_Label('1009', '0')
Process.Stack__Segmentation__Fill_Label('932', '0')
Process.Stack__Segmentation__Fill_Label('841', '0')
Process.Stack__Segmentation__Fill_Label('291', '0')
Process.Stack__Segmentation__Fill_Label('92', '0')
Process.Stack__Segmentation__Fill_Label('995', '0')
Process.Stack__Segmentation__Fill_Label('418', '0')
Process.Stack__Segmentation__Fill_Label('287', '0')
Process.Stack__Segmentation__Fill_Label('56', '0')
Process.Stack__Segmentation__Fill_Label('914', '0')
Process.Stack__Segmentation__Fill_Label('275', '0')
Process.Stack__Segmentation__Fill_Label('485', '0')
Process.Stack__Segmentation__Fill_Label('417', '0')
Process.Stack__Segmentation__Fill_Label('879', '0')
Process.Stack__Segmentation__Fill_Label('712', '0')
Process.Stack__Segmentation__Fill_Label('120', '0')
Process.Stack__Segmentation__Fill_Label('122', '0')
Process.Stack__Segmentation__Fill_Label('609', '0')
Process.Stack__Segmentation__Fill_Label('980', '0')
Process.Stack__Segmentation__Fill_Label('129', '0')
Process.Stack__Segmentation__Fill_Label('12', '0')
Process.Stack__Segmentation__Fill_Label('952', '0')
Process.Stack__Segmentation__Fill_Label('227', '0')
Process.Stack__Segmentation__Fill_Label('817', '0')
Process.Stack__Segmentation__Fill_Label('868', '0')
Process.Stack__Segmentation__Fill_Label('967', '0')
Process.Stack__Segmentation__Fill_Label('201', '0')
Process.Stack__Segmentation__Fill_Label('648', '0')
Process.Stack__Segmentation__Fill_Label('545', '0')
Process.Stack__Segmentation__Fill_Label('313', '0')
Process.Stack__Segmentation__Fill_Label('434', '0')
Process.Stack__Segmentation__Fill_Label('216', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('612', '259')
Process.Stack__Segmentation__Fill_Label('207', '259')
Process.Stack__Segmentation__Fill_Label('499', '259')
Process.Stack__Segmentation__Fill_Label('419', '259')
Process.Stack__Segmentation__Fill_Label('508', '259')
Process.Stack__Segmentation__Fill_Label('259', '259')
Process.Stack__Segmentation__Fill_Label('592', '259')
Process.Stack__Segmentation__Fill_Label('259', '259')
Process.Stack__Segmentation__Fill_Label('662', '259')
Process.Stack__Segmentation__Fill_Label('475', '259')
Process.Stack__Segmentation__Fill_Label('875', '259')
Process.Stack__Segmentation__Fill_Label('385', '0')
Process.Stack__Segmentation__Fill_Label('684', '362')
Process.Stack__Segmentation__Fill_Label('834', '362')
Process.Stack__Segmentation__Fill_Label('45', '362')
Process.Stack__Segmentation__Fill_Label('835', '362')
Process.Stack__Segmentation__Fill_Label('338', '362')
Process.Stack__Segmentation__Fill_Label('740', '362')
Process.Stack__Segmentation__Fill_Label('255', '362')
Process.Stack__Segmentation__Fill_Label('447', '362')
Process.Stack__Segmentation__Fill_Label('414', '362')
Process.Stack__Segmentation__Fill_Label('491', '362')
Process.Stack__Segmentation__Fill_Label('828', '362')
Process.Stack__Segmentation__Fill_Label('362', '362')
Process.Stack__Segmentation__Fill_Label('646', '362')
Process.Stack__Segmentation__Fill_Label('61', '362')
Process.Stack__Segmentation__Fill_Label('190', '362')
Process.Stack__Segmentation__Fill_Label('643', '362')
Process.Stack__Segmentation__Fill_Label('942', '362')
Process.Stack__Segmentation__Fill_Label('59', '362')
Process.Stack__Segmentation__Fill_Label('977', '362')
Process.Stack__Segmentation__Fill_Label('362', '362')
Process.Stack__Segmentation__Fill_Label('999', '362')
Process.Stack__Segmentation__Fill_Label('51', '362')
Process.Stack__Segmentation__Fill_Label('362', '362')
Process.Stack__Segmentation__Fill_Label('362', '362')
Process.Stack__Segmentation__Fill_Label('362', '362')
Process.Stack__Segmentation__Fill_Label('362', '362')
Process.Stack__Segmentation__Fill_Label('66', '362')
Process.Stack__Segmentation__Fill_Label('362', '362')
Process.Stack__Segmentation__Fill_Label('170', '362')
Process.Stack__Segmentation__Fill_Label('535', '259')
Process.Stack__Segmentation__Fill_Label('700', '259')
Process.Stack__Segmentation__Fill_Label('760', '259')
Process.Stack__Segmentation__Fill_Label('238', '259')
Process.Stack__Segmentation__Fill_Label('28', '259')
Process.Stack__Segmentation__Fill_Label('259', '259')
Process.Stack__Segmentation__Fill_Label('826', '259')
Process.Stack__Segmentation__Fill_Label('934', '259')
Process.Stack__Segmentation__Fill_Label('913', '259')
Process.Stack__Segmentation__Fill_Label('1013', '259')
Process.Stack__Segmentation__Fill_Label('125', '259')
Process.Stack__Segmentation__Fill_Label('732', '259')
Process.Stack__Segmentation__Fill_Label('54', '259')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('1008', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('530', '0')
Process.Stack__Segmentation__Fill_Label('497', '0')
Process.Stack__Segmentation__Fill_Label('20', '0')
Process.Stack__Segmentation__Fill_Label('186', '0')
Process.Stack__Segmentation__Fill_Label('510', '0')
Process.Stack__Segmentation__Fill_Label('259', '0')
Process.Stack__Segmentation__Fill_Label('924', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_6/Ac_DA_2_6_2023_09_11__14_02_09_Out.tif', 'Work', '0', '')
Process.Stack__Segmentation__Fill_Label('924', '0')
Process.Stack__Segmentation__Fill_Label('652', '0')
Process.Stack__Segmentation__Fill_Label('510', '0')
Process.Stack__Segmentation__Fill_Label('186', '0')
Process.Stack__Segmentation__Fill_Label('20', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('497', '0')
Process.Stack__Segmentation__Fill_Label('1008', '0')
Process.Stack__Segmentation__Fill_Label('530', '0')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__Segmentation__Fill_Label('1017', '362')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Stack__Segmentation__Fill_Label('362', '473')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Stack__Segmentation__Fill_Label('134', '7')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:12:04
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_mesh.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:17:34
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_mesh.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:19:53

Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_2023_09_11__14_02_09_Out_seg.tif', 'Main', '0', '')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Segmentation__Fill_Label('259', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Segmentation__Fill_Label('1008', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('530', '0')
Process.Stack__Segmentation__Fill_Label('186', '0')
Process.Stack__Segmentation__Fill_Label('497', '0')
Process.Stack__Segmentation__Fill_Label('20', '0')
Process.Stack__Segmentation__Fill_Label('510', '0')
Process.Stack__Segmentation__Fill_Label('652', '0')
Process.Stack__Segmentation__Fill_Label('924', '0')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__Segmentation__Fill_Label('1017', '362')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__Segmentation__Fill_Label('473', '362')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
Process.Stack__Segmentation__Fill_Label('134', '7')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Structure__Smooth_Mesh('1', 'No')
Process.Mesh__Structure__Smooth_Mesh('1', 'No')
Process.Mesh__Structure__Smooth_Mesh('1', 'No')
Process.Mesh__Structure__Smooth_Mesh('1', 'No')
Process.Mesh__Structure__Smooth_Mesh('1', 'No')
Process.Mesh__Structure__Smooth_Mesh('1', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__Structure__Smooth_Mesh('5', 'No')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Stack__Segmentation__Fill_Label('988', '362')
Process.Stack__Segmentation__Fill_Label('488', '362')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-04 10:06:34
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh_a.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh_b.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh_a.mgxm', 'no', 'no', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_7/Ac_DA_2_7_mesh.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-04 10:07:52
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh_b.mgxm', 'no', 'no', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_7/Ac_DA_2_7_mesh_a.mgxm', 'no', 'no', '0')
