######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 14:33:55
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_3/Ac_DA_1_3_2023_09_11__13_21_44_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('93', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('30', '0')
Process.Stack__Segmentation__Fill_Label('48', '0')
Process.Stack__Segmentation__Fill_Label('81', '0')
Process.Stack__Segmentation__Fill_Label('52', '0')
Process.Stack__Segmentation__Fill_Label('110', '0')
Process.Stack__Segmentation__Fill_Label('73', '0')
Process.Stack__Segmentation__Fill_Label('38', '0')
Process.Stack__Segmentation__Fill_Label('97', '0')
Process.Stack__Segmentation__Fill_Label('112', '0')
Process.Stack__Segmentation__Fill_Label('60', '0')
Process.Stack__Segmentation__Fill_Label('14', '0')
Process.Stack__Segmentation__Fill_Label('99', '0')
Process.Stack__Segmentation__Fill_Label('16', '0')
Process.Stack__Segmentation__Fill_Label('27', '0')
Process.Stack__Segmentation__Fill_Label('34', '0')
Process.Stack__Segmentation__Fill_Label('106', '0')
Process.Stack__Segmentation__Fill_Label('15', '0')
Process.Stack__Segmentation__Fill_Label('70', '0')
Process.Stack__Segmentation__Fill_Label('92', '0')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__Segmentation__Fill_Label('18', '0')
Process.Stack__Segmentation__Fill_Label('42', '0')
Process.Stack__Segmentation__Fill_Label('95', '0')
Process.Stack__Segmentation__Fill_Label('24', '0')
Process.Stack__Segmentation__Fill_Label('115', '0')
Process.Stack__Segmentation__Fill_Label('87', '0')
Process.Stack__Segmentation__Fill_Label('10', '0')
Process.Stack__Segmentation__Fill_Label('77', '0')
Process.Stack__Segmentation__Fill_Label('123', '0')
Process.Stack__Segmentation__Fill_Label('65', '0')
Process.Stack__Segmentation__Fill_Label('40', '0')
Process.Stack__Segmentation__Fill_Label('118', '0')
Process.Stack__Segmentation__Fill_Label('76', '59')
Process.Stack__Segmentation__Fill_Label('55', '59')
Process.Stack__Segmentation__Fill_Label('59', '59')
Process.Stack__Segmentation__Fill_Label('117', '59')
Process.Stack__Segmentation__Fill_Label('102', '59')
Process.Stack__Segmentation__Fill_Label('109', '59')
Process.Stack__Segmentation__Fill_Label('50', '59')
Process.Stack__Segmentation__Fill_Label('94', '23')
Process.Stack__Segmentation__Fill_Label('111', '23')
Process.Stack__Segmentation__Fill_Label('114', '23')
Process.Stack__Segmentation__Fill_Label('79', '23')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Stack__Segmentation__Fill_Label('59', '3')
Process.Stack__Segmentation__Fill_Label('85', '3')
Process.Stack__Segmentation__Fill_Label('20', '3')
Process.Stack__Segmentation__Fill_Label('6', '3')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 14:40:46
Process.Misc__System__Save_View('')
Process.Mesh__System__Reset('-1')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_3/Ac_DA_1_3_final.mgxv')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-15 12:06:13
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_3/Ac_DA_1_3_final.mgxv')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_4/Ac_DA_1_4_final.mgxv')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_3/Ac_DA_1_3_final.mgxv')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-28 10:19:37
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_3/Ac_DA_1_3_final.mgxv')
Process.Stack__Canvas__Change_Voxel_Size('0.3', '0.3', '0.6')
Process.Stack__Canvas__Change_Voxel_Size('0.3', '0.3', '0.3')
Process.Stack__Canvas__Change_Voxel_Size('0.3', '0.3', '0.3')
Process.Stack__Canvas__Change_Voxel_Size('0.3', '0.3', '0.6')
Process.Stack__Canvas__Change_Voxel_Size('0.3', '0.3', '1')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-28 11:58:21
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_3/Ac_DA_1_3_2023_09_11__13_21_44_Out_seg.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_3/Ac_DA_1_3_2023_09_11__13_21_44_Out.tif', 'Main', '0', '')
