######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 14:41:36

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1200')
Process.Stack__Segmentation__Fill_Label('45', '0')
Process.Stack__Segmentation__Fill_Label('77', '0')
Process.Stack__Segmentation__Fill_Label('222', '0')
Process.Stack__Segmentation__Fill_Label('124', '0')
Process.Stack__Segmentation__Fill_Label('58', '0')
Process.Stack__Segmentation__Fill_Label('11', '0')
Process.Stack__Segmentation__Fill_Label('108', '0')
Process.Stack__Segmentation__Fill_Label('181', '0')
Process.Stack__Segmentation__Fill_Label('46', '0')
Process.Stack__Segmentation__Fill_Label('191', '0')
Process.Stack__Segmentation__Fill_Label('156', '0')
Process.Stack__Segmentation__Fill_Label('22', '0')
Process.Stack__Segmentation__Fill_Label('148', '0')
Process.Stack__Segmentation__Fill_Label('12', '0')
Process.Stack__Segmentation__Fill_Label('207', '0')
Process.Stack__Segmentation__Fill_Label('136', '0')
Process.Stack__Segmentation__Fill_Label('182', '0')
Process.Stack__Segmentation__Fill_Label('183', '0')
Process.Stack__Segmentation__Fill_Label('223', '0')
Process.Stack__Segmentation__Fill_Label('117', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('135', '0')
Process.Stack__Segmentation__Fill_Label('74', '0')
Process.Stack__Segmentation__Fill_Label('72', '0')
Process.Stack__Segmentation__Fill_Label('164', '0')
Process.Stack__Segmentation__Fill_Label('214', '0')
Process.Stack__Segmentation__Fill_Label('143', '0')
Process.Stack__Segmentation__Fill_Label('20', '0')
Process.Stack__Segmentation__Fill_Label('153', '0')
Process.Stack__Segmentation__Fill_Label('134', '0')
Process.Stack__Segmentation__Fill_Label('33', '0')
Process.Stack__Segmentation__Fill_Label('114', '0')
Process.Stack__Segmentation__Fill_Label('195', '0')
Process.Stack__Segmentation__Fill_Label('26', '0')
Process.Stack__Segmentation__Fill_Label('123', '0')
Process.Stack__Segmentation__Fill_Label('104', '0')
Process.Stack__Segmentation__Fill_Label('169', '0')
Process.Stack__Segmentation__Fill_Label('147', '0')
Process.Stack__Segmentation__Fill_Label('38', '91')
Process.Stack__Segmentation__Fill_Label('106', '91')
Process.Stack__Segmentation__Fill_Label('65', '91')
Process.Stack__Segmentation__Fill_Label('177', '91')
Process.Stack__Segmentation__Fill_Label('144', '91')
Process.Stack__Segmentation__Fill_Label('71', '0')
Process.Stack__Segmentation__Fill_Label('119', '116')
Process.Stack__Segmentation__Fill_Label('91', '116')
Process.Stack__Segmentation__Fill_Label('60', '116')
Process.Stack__Segmentation__Fill_Label('56', '116')
Process.Stack__Segmentation__Fill_Label('98', '53')
Process.Stack__Segmentation__Fill_Label('151', '53')
Process.Stack__Segmentation__Fill_Label('82', '53')
Process.Stack__Segmentation__Fill_Label('105', '53')
Process.Stack__Segmentation__Fill_Label('66', '53')
Process.Stack__Segmentation__Fill_Label('116', '23')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 15:04:43
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-15 12:06:28
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_4/Ac_DA_1_4_final.mgxv')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_5/Ac_DA_1_5_mesh.mgxv')
