######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 10:24:23

Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('119', '0')
Process.Stack__Segmentation__Fill_Label('176', '0')
Process.Stack__Segmentation__Fill_Label('170', '0')
Process.Stack__Segmentation__Fill_Label('106', '0')
Process.Stack__Segmentation__Fill_Label('195', '0')
Process.Stack__Segmentation__Fill_Label('102', '0')
Process.Stack__Segmentation__Fill_Label('89', '0')
Process.Stack__Segmentation__Fill_Label('54', '0')
Process.Stack__Segmentation__Fill_Label('191', '0')
Process.Stack__Segmentation__Fill_Label('34', '0')
Process.Stack__Segmentation__Fill_Label('83', '0')
Process.Stack__Segmentation__Fill_Label('7', '0')
Process.Stack__Segmentation__Fill_Label('192', '0')
Process.Stack__Segmentation__Fill_Label('99', '0')
Process.Stack__Segmentation__Fill_Label('139', '0')
Process.Stack__Segmentation__Fill_Label('93', '0')
Process.Stack__Segmentation__Fill_Label('30', '0')
Process.Stack__Segmentation__Fill_Label('172', '0')
Process.Stack__Segmentation__Fill_Label('144', '0')
Process.Stack__Segmentation__Fill_Label('193', '0')
Process.Stack__Segmentation__Fill_Label('69', '0')
Process.Stack__Segmentation__Fill_Label('168', '0')
Process.Stack__Segmentation__Fill_Label('118', '0')
Process.Stack__Segmentation__Fill_Label('112', '0')
Process.Stack__Segmentation__Fill_Label('158', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('43', '0')
Process.Stack__Segmentation__Fill_Label('92', '0')
Process.Stack__Segmentation__Fill_Label('5', '0')
Process.Stack__Segmentation__Fill_Label('63', '0')
Process.Stack__Segmentation__Fill_Label('61', '0')
Process.Stack__Segmentation__Fill_Label('79', '0')
Process.Stack__Segmentation__Fill_Label('203', '0')
Process.Stack__Segmentation__Fill_Label('4', '114')
Process.Stack__Segmentation__Fill_Label('44', '114')
Process.Stack__Segmentation__Fill_Label('108', '114')
Process.Stack__Segmentation__Fill_Label('32', '67')
Process.Stack__Segmentation__Fill_Label('134', '67')
Process.Stack__Segmentation__Fill_Label('67', '67')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Color_Gradient('5.0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_6/Ac_DA_3_6_2023_09_11__14_35_46_Out.tif', 'Main', '0', '')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_6/Ac_DA_3_6_2023_09_11__14_35_46_Out.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_6/Ac_DA_3_6_2023_09_11__14_35_46_Out.tif', 'Work', '0', '')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 10:42:12
Process.Misc__System__Save_View('')
