######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 10:10:10

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('16.0')
Process.Stack__Filters__Brighten_Darken('16.0')
Process.Stack__Filters__Brighten_Darken('16.0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Color_Gradient('5.0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_3/Ac_DA_3_3_2023_09_11__14_24_49_Out.tif', 'Work', '0', '')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('20', '0')
Process.Stack__Segmentation__Fill_Label('30', '0')
Process.Stack__Segmentation__Fill_Label('10', '0')
Process.Stack__Segmentation__Fill_Label('181', '0')
Process.Stack__Segmentation__Fill_Label('125', '0')
Process.Stack__Segmentation__Fill_Label('121', '0')
Process.Stack__Segmentation__Fill_Label('76', '0')
Process.Stack__Segmentation__Fill_Label('112', '0')
Process.Stack__Segmentation__Fill_Label('124', '0')
Process.Stack__Segmentation__Fill_Label('6', '0')
Process.Stack__Segmentation__Fill_Label('4', '0')
Process.Stack__Segmentation__Fill_Label('91', '0')
Process.Stack__Segmentation__Fill_Label('49', '0')
Process.Stack__Segmentation__Fill_Label('166', '0')
Process.Stack__Segmentation__Fill_Label('78', '0')
Process.Stack__Segmentation__Fill_Label('128', '0')
Process.Stack__Segmentation__Fill_Label('172', '0')
Process.Stack__Segmentation__Fill_Label('168', '0')
Process.Stack__Segmentation__Fill_Label('97', '0')
Process.Stack__Segmentation__Fill_Label('158', '0')
Process.Stack__Segmentation__Fill_Label('93', '0')
Process.Stack__Segmentation__Fill_Label('161', '0')
Process.Stack__Segmentation__Fill_Label('33', '0')
Process.Stack__Segmentation__Fill_Label('84', '0')
Process.Stack__Segmentation__Fill_Label('81', '0')
Process.Stack__Segmentation__Fill_Label('103', '0')
Process.Stack__Segmentation__Fill_Label('174', '0')
Process.Stack__Segmentation__Fill_Label('138', '0')
Process.Stack__Segmentation__Fill_Label('105', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__Segmentation__Fill_Label('44', '0')
Process.Stack__Segmentation__Fill_Label('35', '0')
Process.Stack__Segmentation__Fill_Label('157', '0')
Process.Stack__Segmentation__Fill_Label('162', '0')
Process.Stack__Segmentation__Fill_Label('108', '0')
Process.Stack__Segmentation__Fill_Label('60', '0')
Process.Stack__Segmentation__Fill_Label('58', '0')
Process.Stack__Segmentation__Fill_Label('131', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 10:15:57
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-06 16:18:41

Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_3/Ac_DA_3_7/Ac_DA_3_7_mesh.mgxm', 'no', 'no', '0')
Process.Misc__System__Load_View('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_3/Ac_DA_2_3_final.mgxv')
