######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 09:35:49

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('248', '0')
Process.Stack__Segmentation__Fill_Label('190', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out.tif', 'Work', '0', '')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('316', '0')
Process.Stack__Segmentation__Fill_Label('141', '0')
Process.Stack__Segmentation__Fill_Label('241', '0')
Process.Stack__Segmentation__Fill_Label('159', '0')
Process.Stack__Segmentation__Fill_Label('254', '0')
Process.Stack__Segmentation__Fill_Label('14', '0')
Process.Stack__Segmentation__Fill_Label('55', '0')
Process.Stack__Segmentation__Fill_Label('11', '0')
Process.Stack__Segmentation__Fill_Label('67', '0')
Process.Stack__Segmentation__Fill_Label('194', '0')
Process.Stack__Segmentation__Fill_Label('248', '0')
Process.Stack__Segmentation__Fill_Label('36', '0')
Process.Stack__Segmentation__Fill_Label('220', '0')
Process.Stack__Segmentation__Fill_Label('309', '0')
Process.Stack__Segmentation__Fill_Label('57', '0')
Process.Stack__Segmentation__Fill_Label('268', '0')
Process.Stack__Segmentation__Fill_Label('110', '0')
Process.Stack__Segmentation__Fill_Label('187', '0')
Process.Stack__Segmentation__Fill_Label('306', '0')
Process.Stack__Segmentation__Fill_Label('325', '0')
Process.Stack__Segmentation__Fill_Label('87', '0')
Process.Stack__Segmentation__Fill_Label('153', '0')
Process.Stack__Segmentation__Fill_Label('315', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out.tif', 'Work', '0', '')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1200')
Process.Stack__Segmentation__Fill_Label('73', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('66', '0')
Process.Stack__Segmentation__Fill_Label('150', '0')
Process.Stack__Segmentation__Fill_Label('128', '0')
Process.Stack__Segmentation__Fill_Label('209', '0')
Process.Stack__Segmentation__Fill_Label('279', '0')
Process.Stack__Segmentation__Fill_Label('26', '0')
Process.Stack__Segmentation__Fill_Label('237', '0')
Process.Stack__Segmentation__Fill_Label('317', '0')
Process.Stack__Segmentation__Fill_Label('60', '0')
Process.Stack__Segmentation__Fill_Label('46', '0')
Process.Stack__Segmentation__Fill_Label('139', '0')
Process.Stack__Segmentation__Fill_Label('250', '0')
Process.Stack__Segmentation__Fill_Label('207', '0')
Process.Stack__Segmentation__Fill_Label('270', '0')
Process.Stack__Segmentation__Fill_Label('28', '0')
Process.Stack__Segmentation__Fill_Label('42', '0')
Process.Stack__Segmentation__Fill_Label('130', '0')
Process.Stack__Segmentation__Fill_Label('169', '0')
Process.Stack__Segmentation__Fill_Label('296', '0')
Process.Stack__Segmentation__Fill_Label('236', '0')
Process.Stack__Segmentation__Fill_Label('257', '0')
Process.Stack__Segmentation__Fill_Label('224', '0')
Process.Stack__Segmentation__Fill_Label('99', '0')
Process.Stack__Segmentation__Fill_Label('340', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('144', '0')
Process.Stack__Segmentation__Fill_Label('275', '0')
Process.Stack__Segmentation__Fill_Label('166', '0')
Process.Stack__Segmentation__Fill_Label('196', '0')
Process.Stack__Segmentation__Fill_Label('283', '0')
Process.Stack__Segmentation__Fill_Label('105', '0')
Process.Stack__Segmentation__Fill_Label('216', '0')
Process.Stack__Segmentation__Fill_Label('109', '0')
Process.Stack__Segmentation__Fill_Label('44', '0')
Process.Stack__Segmentation__Fill_Label('170', '0')
Process.Stack__Segmentation__Fill_Label('24', '0')
Process.Stack__Segmentation__Fill_Label('256', '0')
Process.Stack__Segmentation__Fill_Label('11', '0')
Process.Stack__Segmentation__Fill_Label('297', '0')
Process.Stack__Segmentation__Fill_Label('68', '0')
Process.Stack__Segmentation__Fill_Label('274', '0')
Process.Stack__Segmentation__Fill_Label('214', '0')
Process.Stack__Segmentation__Fill_Label('87', '0')
Process.Stack__Segmentation__Fill_Label('122', '0')
Process.Stack__Segmentation__Fill_Label('322', '0')
Process.Stack__Segmentation__Fill_Label('65', '0')
Process.Stack__Segmentation__Fill_Label('103', '0')
Process.Stack__Segmentation__Fill_Label('258', '0')
Process.Stack__Segmentation__Fill_Label('153', '0')
Process.Stack__Segmentation__Fill_Label('314', '0')
Process.Stack__Segmentation__Fill_Label('75', '0')
Process.Stack__Segmentation__Fill_Label('154', '0')
Process.Stack__Segmentation__Fill_Label('325', '0')
Process.Stack__Segmentation__Fill_Label('222', '0')
Process.Stack__Segmentation__Fill_Label('316', '0')
Process.Stack__Segmentation__Fill_Label('56', '0')
Process.Stack__Segmentation__Fill_Label('298', '0')
Process.Stack__Segmentation__Fill_Label('232', '0')
Process.Stack__Segmentation__Fill_Label('51', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('235', '0')
Process.Stack__Segmentation__Fill_Label('94', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('331', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out.tif', 'Work', '0', '')
Process.Stack__Segmentation__Fill_Label('331', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out.tif', 'Work', '0', '')
Process.Stack__Segmentation__Fill_Label('331', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('253', '315')
Process.Stack__Segmentation__Fill_Label('115', '315')
Process.Stack__Segmentation__Fill_Label('80', '315')
Process.Stack__Segmentation__Fill_Label('291', '315')
Process.Stack__Segmentation__Fill_Label('146', '39')
Process.Stack__Segmentation__Fill_Label('191', '39')
Process.Stack__Segmentation__Fill_Label('219', '39')
Process.Stack__Segmentation__Fill_Label('124', '39')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('9', '102')
Process.Stack__Segmentation__Fill_Label('34', '102')
Process.Stack__Segmentation__Fill_Label('265', '102')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:12:13
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_mesh.mgxm', 'no', 'no', '0')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out.tif', 'Main', '0', '')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Diff_Gaussians('0.3', '0.3', '0.3', '2', '2', '2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out_CNN_seg2.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out_CNN_seg1.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_2023_09_11__14_06_12_Out_CNN.tif', 'Main', '0', '')
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_5/Ac_DA_2_5_2023_09_11__13_58_58_Out.tif', 'Main', '0', '')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-03 13:17:59
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/X/Ac_DA_2_7/Ac_DA_2_7_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__Structure__Delete_Selection()
Process.Mesh__System__Save('', 'No', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-04 10:07:31
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_7/Ac_DA_2_7_mesh.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_6/Ac_DA_2_6_mesh_b.mgxm', 'no', 'no', '0')
######## New MorphoGraphX session v2.0 r1-189: 2023-10-04 10:08:33
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_2/Ac_DA_2_7/Ac_DA_2_7_mesh_a.mgxm', 'no', 'no', '0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_6/Ac_DA_1_6_mesh.mgxm', 'no', 'no', '0')
