######## New MorphoGraphX session v2.0 r1-189: 2023-09-13 15:25:31

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1500')
Process.Stack__Segmentation__Fill_Label('162', '0')
Process.Stack__Segmentation__Fill_Label('354', '0')
Process.Stack__Segmentation__Fill_Label('34', '0')
Process.Stack__Segmentation__Fill_Label('75', '0')
Process.Stack__Segmentation__Fill_Label('313', '0')
Process.Stack__Segmentation__Fill_Label('408', '0')
Process.Stack__Segmentation__Fill_Label('237', '0')
Process.Stack__Segmentation__Fill_Label('282', '0')
Process.Stack__Segmentation__Fill_Label('288', '0')
Process.Stack__Segmentation__Fill_Label('241', '0')
Process.Stack__Segmentation__Fill_Label('160', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('51', '0')
Process.Stack__Segmentation__Fill_Label('33', '0')
Process.Stack__Segmentation__Fill_Label('27', '0')
Process.Stack__Segmentation__Fill_Label('75', '0')
Process.Stack__Segmentation__Fill_Label('55', '0')
Process.Stack__Segmentation__Fill_Label('152', '0')
Process.Stack__Segmentation__Fill_Label('29', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
Process.Stack__Filters__Gaussian_Blur_Stack('0.3', '0.3', '0.3')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__ITK__Segmentation__ITK_Watershed_Auto_Seeded('No', 'No', '1000')
Process.Stack__Segmentation__Fill_Label('145', '0')
Process.Stack__Segmentation__Fill_Label('405', '0')
Process.Stack__Segmentation__Fill_Label('628', '0')
Process.Stack__Segmentation__Fill_Label('652', '0')
Process.Stack__Segmentation__Fill_Label('408', '0')
Process.Stack__Segmentation__Fill_Label('176', '0')
Process.Stack__Segmentation__Fill_Label('191', '0')
Process.Stack__Segmentation__Fill_Label('37', '0')
Process.Stack__Segmentation__Fill_Label('139', '0')
Process.Stack__Segmentation__Fill_Label('186', '0')
Process.Stack__Segmentation__Fill_Label('59', '0')
Process.Stack__Segmentation__Fill_Label('590', '0')
Process.Stack__Segmentation__Fill_Label('610', '0')
Process.Stack__Segmentation__Fill_Label('275', '0')
Process.Stack__Segmentation__Fill_Label('236', '0')
Process.Stack__Segmentation__Fill_Label('113', '0')
Process.Stack__Segmentation__Fill_Label('477', '0')
Process.Stack__Segmentation__Fill_Label('544', '0')
Process.Stack__Segmentation__Fill_Label('131', '0')
Process.Stack__Segmentation__Fill_Label('374', '0')
Process.Stack__Segmentation__Fill_Label('446', '0')
Process.Stack__Segmentation__Fill_Label('557', '0')
Process.Stack__Segmentation__Fill_Label('128', '0')
Process.Stack__Segmentation__Fill_Label('286', '0')
Process.Stack__Segmentation__Fill_Label('265', '0')
Process.Stack__Segmentation__Fill_Label('479', '0')
Process.Stack__Segmentation__Fill_Label('254', '0')
Process.Stack__Segmentation__Fill_Label('424', '0')
Process.Stack__Segmentation__Fill_Label('39', '0')
Process.Stack__Segmentation__Fill_Label('421', '0')
Process.Stack__Segmentation__Fill_Label('242', '0')
Process.Stack__Segmentation__Fill_Label('3', '0')
Process.Stack__Segmentation__Fill_Label('169', '0')
Process.Stack__Segmentation__Fill_Label('643', '0')
Process.Stack__Segmentation__Fill_Label('193', '0')
Process.Stack__Segmentation__Fill_Label('412', '0')
Process.Stack__Segmentation__Fill_Label('514', '0')
Process.Stack__Segmentation__Fill_Label('542', '0')
Process.Stack__Segmentation__Fill_Label('334', '0')
Process.Stack__Segmentation__Fill_Label('487', '0')
Process.Stack__Segmentation__Fill_Label('80', '0')
Process.Stack__Segmentation__Fill_Label('36', '0')
Process.Stack__Segmentation__Fill_Label('28', '0')
Process.Stack__Segmentation__Fill_Label('613', '0')
Process.Stack__Segmentation__Fill_Label('141', '0')
Process.Stack__Segmentation__Fill_Label('595', '0')
Process.Stack__Segmentation__Fill_Label('120', '0')
Process.Stack__Segmentation__Fill_Label('522', '0')
Process.Stack__Segmentation__Fill_Label('85', '0')
Process.Stack__Segmentation__Fill_Label('53', '0')
Process.Stack__Segmentation__Fill_Label('127', '0')
Process.Stack__Segmentation__Fill_Label('163', '0')
Process.Stack__Segmentation__Fill_Label('346', '0')
Process.Stack__Segmentation__Fill_Label('200', '0')
Process.Stack__Segmentation__Fill_Label('400', '0')
Process.Stack__Segmentation__Fill_Label('245', '0')
Process.Stack__Segmentation__Fill_Label('536', '0')
Process.Stack__Segmentation__Fill_Label('124', '0')
Process.Stack__Segmentation__Fill_Label('349', '0')
Process.Stack__Segmentation__Fill_Label('348', '0')
Process.Stack__Segmentation__Fill_Label('138', '0')
Process.Stack__Segmentation__Fill_Label('627', '0')
Process.Stack__Segmentation__Fill_Label('79', '0')
Process.Stack__Segmentation__Fill_Label('636', '0')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Stack__Segmentation__Fill_Label('293', '0')
Process.Stack__Segmentation__Fill_Label('383', '0')
Process.Stack__Segmentation__Fill_Label('600', '0')
Process.Stack__Segmentation__Fill_Label('602', '0')
Process.Stack__Segmentation__Fill_Label('545', '0')
Process.Stack__Segmentation__Fill_Label('62', '0')
Process.Stack__Segmentation__Fill_Label('435', '0')
Process.Stack__Segmentation__Fill_Label('140', '0')
Process.Stack__Segmentation__Fill_Label('122', '0')
Process.Stack__Segmentation__Fill_Label('579', '0')
Process.Stack__Segmentation__Fill_Label('285', '566')
Process.Stack__Segmentation__Fill_Label('234', '566')
Process.Stack__Segmentation__Fill_Label('148', '566')
Process.Stack__Segmentation__Fill_Label('210', '566')
Process.Stack__Segmentation__Fill_Label('500', '566')
Process.Stack__Segmentation__Fill_Label('460', '566')
Process.Stack__Segmentation__Fill_Label('499', '566')
Process.Stack__Segmentation__Fill_Label('330', '566')
Process.Stack__Segmentation__Fill_Label('233', '566')
Process.Stack__Segmentation__Fill_Label('493', '566')
Process.Stack__Segmentation__Fill_Label('14', '566')
Process.Stack__Segmentation__Fill_Label('211', '566')
Process.Stack__Segmentation__Fill_Label('599', '589')
Process.Stack__Segmentation__Fill_Label('483', '589')
Process.Stack__Segmentation__Fill_Label('15', '589')
Process.Stack__Segmentation__Fill_Label('620', '589')
Process.Stack__Segmentation__Fill_Label('212', '589')
Process.Stack__Segmentation__Fill_Label('301', '566')
Process.Stack__Segmentation__Fill_Label('143', '589')
Process.Stack__System__Save('', 'Work', '0', '5', '/label')
Process.Mesh__Creation__Marching_Cubes_3D('1', '0', '3', '0')
Process.Mesh__System__Save('', 'No', '0')
Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__Filters__Brighten_Darken('2')
Process.Stack__CNN__UNet3D_Prediction('/usr/share/MorphoGraphX/CNN', '128 128 128', '0.5', '0 0 0', '1.0 1.0 1.0', '2', 'No', 'Yes')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-29 09:55:28

Process.Stack__MultiStack__Copy_Main_to_Work_Stack()
Process.Stack__System__Open('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_8/Ac_DA_1_8_2023_09_11__13_41_00_Out.tif', 'Main', '0', '')
Process.Mesh__System__Load('/media/bitlockermount/Stomata project/Confocal data/Experiment 16 - Onion/Ac_DA_1/Ac_DA_1_8/Ac_DA_1_8_mesh.mgxm', 'no', 'no', '0')
Process.Misc__System__Save_View('')
######## New MorphoGraphX session v2.0 r1-189: 2023-09-29 09:56:01
Process.Misc__System__Save_View('')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
Process.Mesh__Heat_Map__Heat_Map_Classic('Area', 'Geometry', '', 'Geometry', 'No', '0', '65535', 'Yes', 'No', 'None', 'No', 'Increasing', 'Ratio', '.001', '1.0')
