######## New MorphoDynamX session v2.0 r3-74: 2025-07-23 10:16:18
Process.Tools__System__Save_View('/usr/users/JIC_a5/tomkinsm/.vlab/tmp/VLHf3uSe/FemMembranes.mdxv')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Mesh__Segmentation__Set_Label('2', '', '', 'All')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Mesh__Segmentation__Set_Label('15', '', '', 'All')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Mesh__Segmentation__Set_Label('15', '', '', 'All')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Tools__System__Load_View('/usr/users/JIC_a5/tomkinsm/stomata-air-mattress/Meshes/Idealised/Onion_1_2.mdxv')
Process.Tools__System__Load_View('/usr/users/JIC_a5/tomkinsm/stomata-air-mattress/Meshes/Idealised/Onion_1_2.mdxv')
Process.Mesh__Position__Rotate_Mesh('0.0 0.0 0.0', '0.0 1.0 0.0', '-5')
Process.Mesh__Position__Rotate_Mesh('0.0 0.0 0.0', '0.0 1.0 0.0', '-5')
Process.Mesh__Position__Rotate_Mesh('0.0 0.0 0.0', '0.0 1.0 0.0', '-5')
Process.Mesh__Position__Rotate_Mesh('0.0 0.0 0.0', '0.0 1.0 0.0', '-5')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '75', '400', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '5.0', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Stack__System__Delete_Stack('Stack2')
######## New MorphoDynamX session v2.0 r3-74: 2025-07-23 10:51:00
Process.Tools__System__Save_View('/usr/users/JIC_a5/tomkinsm/.vlab/tmp/VLHf3uSe/FemMembranes.mdxv')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Mesh__Position__Translate_Mesh('0.0 0.0 1.0')
Process.Mesh__Position__Translate_Mesh('0.0 0.0 -1.0')
Process.Mesh__Position__Translate_Mesh('0.0 0.0 -1.0')
Process.Mesh__Position__Translate_Mesh('1.0 0.0 0.0')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Mesh__Segmentation__Set_Label('14', '', '', 'All')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack3')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Mesh__Position__Rotate_Mesh('0.0 0.0 0.0', '0.0 1.0 0.0', '-5')
Process.Mesh__Position__Rotate_Mesh('0.0 0.0 0.0', '0.0 1.0 0.0', '-5')
Process.Mesh__Position__Rotate_Mesh('0.0 0.0 0.0', '1.0 0.0 0.0', '-5')
Process.Mesh__Position__Translate_Mesh('0.0 -1.0 0.0')
Process.Mesh__Position__Translate_Mesh('0.0 1.0 0.0')
Process.Mesh__Position__Translate_Mesh('0.0 1.0 0.0')
Process.Tools__System__Save_View('/usr/users/JIC_a5/tomkinsm/stomata-air-mattress/Meshes/Idealised/Onion_1_2.mdxv')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Mesh__Segmentation__Set_Label('14', '', '', 'All')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Position__Translate_Mesh('0.0 1.0 0.0')
Process.Mesh__Position__Translate_Mesh('0.0 -1.0 0.0')
Process.Mesh__Position__Translate_Mesh('0.0 0.0 1.0')
Process.Mesh__Position__Translate_Mesh('0.0 0.0 1.0')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 0', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Stack__System__Delete_Stack('Stack3')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack7')
Process.Stack__System__Delete_Stack('Stack6')
Process.Stack__System__Delete_Stack('Stack5')
Process.Stack__System__Delete_Stack('Stack4')
Process.Stack__System__Delete_Stack('Stack3')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack3')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__06_Set_Ansio_Dir('', '', 'Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Parallel', '1e-6')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Mesh__Position__Center_Mesh()
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__Plugins__Calculate_Pore_Area('0.1', '0.1', 'Yes', 'No')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__05_Set_Material_Properties('', '', '20', '20', '0.3', '1', 'Faces', 'TransIso Material')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '20', '20', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__05_Set_Material_Properties('', '', '50', '50', '0.3', '1', 'Faces', 'TransIso Material')
Process.Mesh__Selection__Action__Invert_Selection('Auto')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Import('', '', 'Imported', 'No', 'No')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 0 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '100', '100', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '2', '1', 'Fem Pressure', 'Triangle Element')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__05_Set_Material_Properties('', '', '80', '80', '0.3', '1', 'Faces', 'TransIso Material')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Stack__System__Delete_Stack('Stack2')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '80', '80', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__07_Set_Pressure('', '', '5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Selection__Action__Clear_Selection('All')
